import type { ExamItem } from '@/content/exam/types';

const bank: ExamItem[] = [
  {
    id: 'arms-x01',
    unitId: 'arms',
    moduleId: 'general-mortgage-knowledge',
    area: 'general',
    pool: 'section',
    stem: "A note is written as a 5/1 ARM. A borrower asks what the two numbers mean. How should the originator explain them?",
    options: [
      'The rate is fixed for 1 year, then adjusts every 5 years',
      'The rate is fixed for 5 years, then adjusts every 1 year after that',
      'The rate can rise 5 points at first, then 1 point a year',
      'The loan has a 5% margin and a 1% index',
    ],
    correct: 1,
    explanation: 'An ARM is written as two numbers — how long the rate stays fixed, then how often it adjusts after that. A 5/1 stays fixed for five years, then adjusts every one year.',
    difficulty: 'recall',
    source: 'reader: ARMs · how an ARM is written',
  },
  {
    id: 'arms-x02',
    unitId: 'arms',
    moduleId: 'general-mortgage-knowledge',
    area: 'general',
    pool: 'section',
    stem: "On an ARM note, one number is the public rate the loan tracks and another is the lender's fixed markup added on top. The lender's fixed markup is the:",
    options: ['index', 'margin', 'start rate', 'initial cap'],
    correct: 1,
    explanation: "The margin is the lender's fixed markup, added to the index; the rate can't fall below it. The index is the public rate the loan tracks; the start rate is the introductory rate.",
    difficulty: 'recall',
    source: 'reader: ARMs · index and margin',
  },
  {
    id: 'arms-x03',
    unitId: 'arms',
    moduleId: 'general-mortgage-knowledge',
    area: 'general',
    pool: 'section',
    stem: "At an ARM's first adjustment, the index sits at 4.00% and the note's margin is 2.50%. What is the fully-indexed rate the loan will charge?",
    options: ['2.50%', '4.00%', '6.50%', '1.50%'],
    correct: 2,
    explanation: 'The fully-indexed rate is the index plus the margin, rounded to the nearest ⅛%: 4.00% + 2.50% = 6.50%. It is not the start rate and not the index alone.',
    difficulty: 'application',
    source: 'reader: ARMs · fully-indexed rate',
  },
  {
    id: 'arms-x04',
    unitId: 'arms',
    moduleId: 'general-mortgage-knowledge',
    area: 'general',
    pool: 'section',
    stem: "A conventional ARM has already made its first adjustment. At the next adjustment, the periodic cap limits how far the rate can move measured from which point?",
    options: [
      'The original start rate',
      'The prior year\'s rate',
      'The life-of-loan ceiling',
      'The fully-indexed rate at closing',
    ],
    correct: 1,
    explanation: 'The periodic cap measures from the prior rate — the most the rate can move at each adjustment after the first. Only the initial and life caps measure from the start rate.',
    difficulty: 'application',
    source: 'reader: ARMs · what the caps do',
  },
  {
    id: 'arms-x05',
    unitId: 'arms',
    moduleId: 'general-mortgage-knowledge',
    area: 'general',
    pool: 'section',
    stem: "A borrower is comparing an FHA ARM with a conventional ARM and asks which cap governs the very first rate adjustment on the FHA loan. What is the answer?",
    options: [
      'The initial adjustment cap',
      'The periodic adjustment cap, because FHA and VA ARMs have no initial cap',
      'The life-of-loan cap',
      'There is no cap on the first adjustment',
    ],
    correct: 1,
    explanation: 'FHA and VA ARMs have no initial cap, so the periodic cap applies to the first adjustment too. On a conventional ARM the initial cap would govern that first move.',
    difficulty: 'application',
    source: 'reader: ARMs · what the caps do',
  },
  {
    id: 'arms-x06',
    unitId: 'arms',
    moduleId: 'general-mortgage-knowledge',
    area: 'general',
    pool: 'section',
    stem: "An ARM's start rate is set a full 4% below its fully-indexed rate. Under the reader's terms, is that a discount rate or a teaser rate?",
    options: [
      'A discount rate, because any below-market start rate is a discount',
      'A teaser rate, because it is more than 3% below the fully-indexed rate',
      'A discount rate, because it is within 3% of the fully-indexed rate',
      'Neither — a start rate can never be more than 3% below',
    ],
    correct: 1,
    explanation: 'Both teaser and discount rates are start rates below the fully-indexed rate. A discount rate is within 3% of it; a teaser rate is more than 3% below. A start rate 4% below the FIAR is a teaser.',
    difficulty: 'analysis',
    source: 'reader: ARMs · teaser vs discount rate',
  },
];

export default bank;
