import type { ExamItem } from '@/content/exam/types';

const bank: ExamItem[] = [
  {
    id: 'bsa-aml-x01',
    unitId: 'bsa-aml',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: "At closing, a buyer hands over a $15,000 earnest-money deposit in physical cash. The institution has to report this single cash transaction to the government. Which report covers it?",
    options: [
      'A Suspicious Activity Report (SAR)',
      'A Currency Transaction Report (CTR)',
      'A Report of Blocked Property',
      'A Customer Identification Program (CIP) filing',
    ],
    correct: 1,
    explanation: "A cash transaction of $10,000 or more is reported on a Currency Transaction Report (CTR), which triggers on the dollar amount alone. A SAR is for activity that looks suspicious, not for an ordinary cash transaction that simply crosses the $10,000 line.",
    difficulty: 'recall',
    source: 'reader: BSA/AML · structuring and the $10,000 line',
  },
  {
    id: 'bsa-aml-x02',
    unitId: 'bsa-aml',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: "A mortgage broker reviewing a loan file spots what looks like fraud, but the dollar amount involved is only about $3,000. Does the broker have to file a SAR?",
    options: [
      'No — a SAR is required only when the amount is $5,000 or more',
      'No — a SAR is required only when the amount is $25,000 or more',
      'Yes — mortgage lenders and brokers have no dollar floor and must file for any suspicious activity',
      'No — only if a specific suspect has already been identified',
    ],
    correct: 2,
    explanation: "For mortgage lenders and brokers there is no dollar threshold at all — any suspicious activity must be reported, regardless of amount. The $5,000 and $25,000 figures are bank SAR thresholds; they do not apply to mortgage professionals.",
    difficulty: 'application',
    source: 'reader: BSA/AML · the dollar thresholds',
  },
  {
    id: 'bsa-aml-x03',
    unitId: 'bsa-aml',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: "A processor identifies suspicious activity but cannot yet name a suspect. The filing can be pushed back to try to identify one. What is the absolute latest a SAR can be filed, measured from the date the activity was spotted?",
    options: [
      '30 days',
      '45 days',
      '60 days',
      '90 days',
    ],
    correct: 2,
    explanation: "The SAR clock is 30 days from discovery, and if no suspect is identified it can extend another 30 days — but never beyond 60 days total. Thirty days is the ordinary deadline, not the maximum after the extension.",
    difficulty: 'application',
    source: 'reader: BSA/AML · report the suspicious',
  },
  {
    id: 'bsa-aml-x04',
    unitId: 'bsa-aml',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: "Before issuing a mortgage, a loan originator screens the applicant and finds the name matches an entry on OFAC's list of Specially Designated Nationals and Blocked Persons. What must the originator do?",
    options: [
      'Proceed with the loan but file a Currency Transaction Report',
      'Not proceed — completing a blocked transaction is itself a violation',
      'Proceed at a higher interest rate to offset the risk',
      'Proceed but require a co-signer on the loan',
    ],
    correct: 1,
    explanation: "A match on the OFAC SDN list is a hard stop: the originator may not proceed, and completing a blocked transaction is itself a violation carrying severe penalties. Charging more or adding a co-signer does not cure a prohibited transaction.",
    difficulty: 'application',
    source: 'reader: BSA/AML · the sanctions list (OFAC)',
  },
  {
    id: 'bsa-aml-x05',
    unitId: 'bsa-aml',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: "An MLO is reviewing four loan files. Which one is the clearest money-laundering red flag that warrants a closer look?",
    options: [
      'A borrower making a 25% down payment from a documented savings account',
      'A cash-out refinance on a property the seller purchased only weeks earlier',
      'A borrower who asks for a 15-year term instead of a 30-year term',
      'A borrower with a high but fully verified salary',
    ],
    correct: 1,
    explanation: "A cash-out refinance of a property the seller only just bought is one of the red flags the unit names, alongside structured sub-$10,000 deposits and mismatched identity details. A large documented down payment, a shorter term, and a verified salary are ordinary features, not red flags.",
    difficulty: 'analysis',
    source: 'reader: BSA/AML · what a red flag looks like',
  },
  {
    id: 'bsa-aml-x06',
    unitId: 'bsa-aml',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: "When a mortgage company files a SAR electronically, which Treasury body receives it and analyzes the reports for patterns as the BSA's administrator?",
    options: [
      'FinCEN — the Financial Crimes Enforcement Network',
      'The OCC — the Office of the Comptroller of the Currency',
      'OFAC — the Office of Foreign Assets Control',
      'The CFPB — the Consumer Financial Protection Bureau',
    ],
    correct: 0,
    explanation: "FinCEN administers the BSA, collects the reports, and hunts for patterns. The OCC examines national banks and OFAC runs the sanctions list — neither is where SARs are filed.",
    difficulty: 'recall',
    source: 'reader: BSA/AML · the agencies, by job',
  },
];

export default bank;
