import type { ExamItem } from '@/content/exam/types';

const bank: ExamItem[] = [
  {
    id: 'construction-rehab-x01',
    unitId: 'construction-rehab',
    moduleId: 'general-mortgage-knowledge',
    area: 'general',
    pool: 'section',
    stem: "A borrower wants a loan to build a house that doesn't exist yet, but a lender won't write a standard mortgage on it. Why, and what fills the gap?",
    options: [
      'The borrower has no down payment; an FHA loan fills the gap',
      'There is no finished collateral to secure the loan; construction financing funds the build in stages',
      'The land is not owned; a bridge loan fills the gap',
      'The rate can\'t be locked; a HELOC fills the gap',
    ],
    correct: 1,
    explanation: "A lender won't write a standard mortgage on a house that doesn't exist yet — there's no finished collateral to secure the loan. Construction financing fills the gap: it funds the build in stages and converts to an ordinary mortgage once the home stands.",
    difficulty: 'recall',
    source: 'reader: construction and rehab · why construction financing exists',
  },
  {
    id: 'construction-rehab-x02',
    unitId: 'construction-rehab',
    moduleId: 'general-mortgage-knowledge',
    area: 'general',
    pool: 'section',
    stem: "A builder finishes framing on a construction loan and requests the next release of funds. What does the lender do before handing over the money?",
    options: [
      'Releases it immediately on request',
      'Inspects the completed work, then releases the draw',
      'Waits until the entire home is complete',
      'Converts the loan to permanent financing first',
    ],
    correct: 1,
    explanation: 'As each phase finishes, the builder requests the next draw; the lender inspects the work before releasing it, and repeats until the home is complete and fully funded.',
    difficulty: 'application',
    source: 'reader: construction and rehab · money released in stages',
  },
  {
    id: 'construction-rehab-x03',
    unitId: 'construction-rehab',
    moduleId: 'general-mortgage-knowledge',
    area: 'general',
    pool: 'section',
    stem: "Halfway through a build, only part of the construction loan has been drawn. How is the borrower billed during the build?",
    options: [
      'Full principal and interest on the entire approved loan',
      'Interest-only, and only on the funds drawn so far',
      'Nothing until the home is complete',
      'A fixed amortizing payment on the land cost',
    ],
    correct: 1,
    explanation: 'During the build the borrower is billed interest-only, and only on the funds drawn so far — not on the full approved amount and not on undrawn funds.',
    difficulty: 'application',
    source: 'reader: construction and rehab · money released in stages',
  },
  {
    id: 'construction-rehab-x04',
    unitId: 'construction-rehab',
    moduleId: 'general-mortgage-knowledge',
    area: 'general',
    pool: 'section',
    stem: "A borrower using construction-to-permanent financing wants to sign for both the build and the permanent mortgage in a single settlement. Which structure is that?",
    options: [
      'Two-close',
      'One-close',
      'A rehab loan',
      'An end loan only',
    ],
    correct: 1,
    explanation: 'One-close settles the build and the permanent loan in a single settlement. Two-close closes the permanent loan separately, in a second settlement.',
    difficulty: 'application',
    source: 'reader: construction and rehab · when the build becomes the mortgage',
  },
  {
    id: 'construction-rehab-x05',
    unitId: 'construction-rehab',
    moduleId: 'general-mortgage-knowledge',
    area: 'general',
    pool: 'section',
    stem: "A borrower building a home wants to lock the permanent rate far in advance to be safe. What does the reader warn about longer rate locks?",
    options: [
      'They are not allowed on construction loans',
      'They get expensive past 90 days, so timing the lock against the build schedule matters',
      'They must be at least one year long',
      'They convert the loan to an ARM',
    ],
    correct: 1,
    explanation: 'Long rate locks are available, but they get expensive past 90 days, so timing the lock against the build schedule matters.',
    difficulty: 'recall',
    source: 'reader: construction and rehab · when the build becomes the mortgage',
  },
  {
    id: 'construction-rehab-x06',
    unitId: 'construction-rehab',
    moduleId: 'general-mortgage-knowledge',
    area: 'general',
    pool: 'section',
    stem: "An investor wants to buy and renovate a rental property (not owner-occupied) with a single rehab loan. Between an FHA 203(k) and a Fannie Mae HomeStyle, which can do it, and why?",
    options: [
      'The 203(k), because it covers all property types',
      'The HomeStyle, because it can also cover investment properties, which the 203(k) can\'t',
      'Either one, since both cover investment properties',
      'Neither, because rehab loans require owner occupancy',
    ],
    correct: 1,
    explanation: 'The conventional HomeStyle (and Freddie Renovation) loans can cover second homes and investment properties. The FHA 203(k) is limited to owner-occupied 1–4 unit properties, so it can\'t finance a non-owner-occupied rental.',
    difficulty: 'analysis',
    source: 'reader: construction and rehab · financing a home that needs work',
  },
];

export default bank;
