import type { ExamItem } from '@/content/exam/types';

const bank: ExamItem[] = [
  {
    id: 'dnc-tsr-x01',
    unitId: 'dnc-tsr',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: "A telemarketing team places sales calls from one state to consumers located in other states. Which agency enforces the Telemarketing Sales Rule for these interstate calls?",
    options: [
      'The FCC',
      'The FTC',
      'The CFPB',
      'The FinCEN',
    ],
    correct: 1,
    explanation: "The FTC handles interstate calls, where caller and recipient are in different states. The FCC handles intrastate calls, where both are in the same state — so it is the wrong enforcer here.",
    difficulty: 'recall',
    source: 'reader: DNC/TSR · the registry',
  },
  {
    id: 'dnc-tsr-x02',
    unitId: 'dnc-tsr',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: "An MLO's marketing group wants to start dialing homeowners at 7:30 a.m. their local time to catch them before work. Is that allowed under the TSR?",
    options: [
      'Yes — there is no time restriction on sales calls',
      'No — residential sales calls may start no earlier than 8 a.m. local time',
      'Yes — as long as the calls end by 9 p.m.',
      'No — calls may only be placed between 9 a.m. and 5 p.m.',
    ],
    correct: 1,
    explanation: "Residential sales calls are boxed into 8 a.m. to 9 p.m. in the called person's local time, so a 7:30 a.m. call is too early. The 9 p.m. cutoff is the other end of the window and does not authorize an early start.",
    difficulty: 'application',
    source: 'reader: DNC/TSR · the abusive line',
  },
  {
    id: 'dnc-tsr-x03',
    unitId: 'dnc-tsr',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: "A seller scrubbed its call list against the Do-Not-Call Registry six weeks ago and has not scrubbed it since. Why is the list now out of compliance?",
    options: [
      'The list must be re-scrubbed every 31 days',
      'The list must be re-scrubbed every 24 hours',
      'The list must be re-scrubbed every 6 months',
      'A list only needs to be scrubbed once',
    ],
    correct: 0,
    explanation: "Numbers come and go, so a telemarketer must re-scrub against the registry every 31 days; six weeks exceeds that. A one-time scrub is never enough, and 24 hours and 6 months are not the required interval.",
    difficulty: 'application',
    source: 'reader: DNC/TSR · scrubbing the list',
  },
  {
    id: 'dnc-tsr-x04',
    unitId: 'dnc-tsr',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: "A consumer's number is on the Do-Not-Call Registry, but she asked the lender about a refinance two months ago. May the lender call her about it?",
    options: [
      'No — a registered number can never be called',
      'Yes — a consumer who inquired within the last 3 months can still be called',
      'No — an inquiry does not create any exception',
      'Yes — but only if she inquired within the last 12 months',
    ],
    correct: 1,
    explanation: "A consumer's inquiry within the last 3 months is one of the calls that escapes the registry. Her inquiry two months ago fits. (A prior purchase would allow calls for 18 months, but that is a different exception.)",
    difficulty: 'application',
    source: 'reader: DNC/TSR · scrubbing the list',
  },
  {
    id: 'dnc-tsr-x05',
    unitId: 'dnc-tsr',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: "A telemarketer demands a fee up front, before delivering a promised loan to the consumer. Under the TSR, this is best classified as which kind of prohibited practice?",
    options: [
      'A deceptive practice',
      'An abusive practice',
      'A permitted practice with disclosure',
      'A recordkeeping violation',
    ],
    correct: 1,
    explanation: "Demanding a fee in advance of delivering a loan or credit is an abusive practice — it is about coercion, not lying. Deceptive practices involve misrepresentation, such as hiding a cost or faking prize odds, which is a different bucket.",
    difficulty: 'analysis',
    source: 'reader: DNC/TSR · the abusive line',
  },
  {
    id: 'dnc-tsr-x06',
    unitId: 'dnc-tsr',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: "During an investigation, regulators ask a telemarketer to produce the scripts, ads, and sales records behind a campaign. For how long must those records have been kept?",
    options: [
      'At least 6 months',
      'At least 12 months',
      'At least 24 months',
      'At least 5 years',
    ],
    correct: 2,
    explanation: "Telemarketers must keep their scripts, ads, and sales records for at least 24 months. The shorter periods fall below the rule's requirement.",
    difficulty: 'recall',
    source: 'reader: DNC/TSR · records and the price of breaking it',
  },
];

export default bank;
