import type { ExamItem } from '@/content/exam/types';

const bank: ExamItem[] = [
  {
    id: 'dodd-frank-x01',
    unitId: 'dodd-frank',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: "An MLO explains that after the 2008 collapse, Congress built a single consumer-finance watchdog housed within the Federal Reserve. Which agency is that, and which law created it?",
    options: [
      'The CFPB, created by the Dodd-Frank Act',
      'The FTC, created by RESPA',
      'The OCC, created by the USA PATRIOT Act',
      'The CFPB, created by TILA',
    ],
    correct: 0,
    explanation: "Dodd-Frank created the Consumer Financial Protection Bureau, an independent bureau housed within the Federal Reserve. TILA, RESPA, and the PATRIOT Act did not create it, and the OCC is a separate, older regulator.",
    difficulty: 'recall',
    source: 'reader: Dodd-Frank · the new referee: the CFPB',
  },
  {
    id: 'dodd-frank-x02',
    unitId: 'dodd-frank',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: "A creditor is underwriting a teaser-rate ARM whose payment will jump after the intro period. Under the ability-to-repay rule, which payment must it use to qualify the borrower?",
    options: [
      'The low introductory teaser payment',
      'A fully amortizing payment — the real, higher payment after the rate resets',
      'An interest-only payment',
      'Whatever payment the borrower asks to be qualified on',
    ],
    correct: 1,
    explanation: "ATR requires the creditor to qualify the borrower on a fully amortizing payment — the real payment after any teaser rate resets — not the low introductory or interest-only one. Qualifying on the teaser payment is precisely the practice ATR was written to stop.",
    difficulty: 'application',
    source: 'reader: Dodd-Frank · what ability-to-repay weighs',
  },
  {
    id: 'dodd-frank-x03',
    unitId: 'dodd-frank',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: "A broker is offered a bigger payout for steering a borrower into a loan with a higher interest rate. Under the loan-originator compensation rule Dodd-Frank created, is that allowed?",
    options: [
      'Yes — compensation can reflect the rate the borrower accepts',
      "No — originator pay can't be based on a loan's terms, only on the loan amount",
      'Yes — as long as the borrower signs a disclosure',
      'No — but only if the borrower qualifies for a Qualified Mortgage',
    ],
    correct: 1,
    explanation: "Dodd-Frank's loan-originator compensation limits bar pay from being based on a loan's terms; it may vary only with the loan amount. Tying a bigger payout to a higher rate is the prohibited arrangement, and no disclosure cures it.",
    difficulty: 'application',
    source: 'reader: Dodd-Frank · where TILA\'s originator rules came from',
  },
  {
    id: 'dodd-frank-x04',
    unitId: 'dodd-frank',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: "A hybrid ARM has a fixed intro period longer than a year before it first adjusts. Roughly when must the creditor or servicer send the written reset warning?",
    options: [
      'About 3 days before the first rate adjustment',
      'About 30 days before the first rate adjustment',
      'About 6 months before the first rate adjustment',
      'About 2 years before the first rate adjustment',
    ],
    correct: 2,
    explanation: "For a hybrid ARM, the reset notice must go out roughly 6 months before the first rate adjustment, estimating the new payment, explaining the index and margin, and listing the borrower's options. Three days and 30 days are far too short.",
    difficulty: 'application',
    source: 'reader: Dodd-Frank · the ARM reset warning',
  },
  {
    id: 'dodd-frank-x05',
    unitId: 'dodd-frank',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: "A lender writes a loan built to meet the ability-to-repay standard by design, without the riskiest features. If the loan's ATR compliance is later challenged, what does making it a Qualified Mortgage give the lender?",
    options: [
      'A guarantee that no borrower can ever default',
      'A presumption that the ability-to-repay rule was satisfied',
      'An exemption from all CFPB supervision',
      'A waiver of the reset-notice requirement',
    ],
    correct: 1,
    explanation: "Making a Qualified Mortgage means the lender is presumed to have satisfied the ability-to-repay rule — the safe harbor that rewards writing the sound loan. It is not a guarantee against default, nor does it exempt the lender from supervision or other disclosures.",
    difficulty: 'analysis',
    source: 'reader: Dodd-Frank · the safe loan: the Qualified Mortgage',
  },
  {
    id: 'dodd-frank-x06',
    unitId: 'dodd-frank',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: "The CFPB is led by a single Director appointed by the President and confirmed by the Senate. How long is that Director's term?",
    options: [
      '2 years',
      '4 years',
      '5 years',
      'a lifetime appointment',
    ],
    correct: 2,
    explanation: "The CFPB Director serves a 5-year term and is removable only for cause. Two- and four-year terms and a lifetime appointment are not what Dodd-Frank set.",
    difficulty: 'recall',
    source: 'reader: Dodd-Frank · the new referee: the CFPB',
  },
];

export default bank;
