import type { ExamItem } from '@/content/exam/types';

const bank: ExamItem[] = [
  {
    id: 'e-sign-act-x01',
    unitId: 'e-sign-act',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: "A borrower types his name into a box on a screen to sign a loan document. Under the E-Sign Act, what makes that typed name an electronic signature?",
    options: [
      'It was witnessed by a notary',
      'It was adopted with the intent to sign the record',
      'It was printed on paper afterward',
      'It matches a handwriting sample on file',
    ],
    correct: 1,
    explanation: "An electronic signature is any electronic sound, symbol, or process attached to a record and adopted with the intent to sign — intent is what makes it a signature. A notary, a paper printout, and a handwriting match are not what E-Sign requires.",
    difficulty: 'recall',
    source: 'reader: E-Sign Act · what counts as a signature now',
  },
  {
    id: 'e-sign-act-x02',
    unitId: 'e-sign-act',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: "A law requires that a certain disclosure reach the borrower in writing. The lender would rather deliver it electronically. What must the lender have before doing so?",
    options: [
      "The borrower's affirmative consent to electronic delivery",
      'A court order permitting electronic delivery',
      'A paper copy mailed first as a backup',
      "The borrower's employer's approval",
    ],
    correct: 0,
    explanation: "Where a law requires information in writing, the lender may deliver it electronically only if the consumer has affirmatively consented and has not withdrawn that consent — nobody can be forced to accept electronic records. A court order or employer approval is not part of E-Sign.",
    difficulty: 'application',
    source: 'reader: E-Sign Act · the consumer has to agree first',
  },
  {
    id: 'e-sign-act-x03',
    unitId: 'e-sign-act',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: "A lender plans to deliver loan documents as PDFs, but the borrower gave consent by mailing back a paper form. Why might that consent fall short under E-Sign?",
    options: [
      'Consent must be notarized to be valid',
      'Consent must reasonably demonstrate the borrower can access the records in the format the lender will use',
      'Consent must be given at least 30 days in advance',
      'Consent must be witnessed by a second party',
    ],
    correct: 1,
    explanation: "E-Sign's key step is that consent must reasonably demonstrate the consumer can actually access the records in the format that will be used — so the borrower typically consents electronically, in that same format, proving they can open the PDF. Paper consent does not prove they can open the electronic files.",
    difficulty: 'application',
    source: 'reader: E-Sign Act · prove they can actually open it',
  },
  {
    id: 'e-sign-act-x04',
    unitId: 'e-sign-act',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: "A borrower clicks an 'I agree' button to accept a loan contract online, meaning it as her acceptance. Later she argues the contract is unenforceable because nothing was signed on paper. Is she right?",
    options: [
      'Yes — only ink on paper can bind a borrower',
      "No — a contract can't be denied legal effect solely because it's electronic",
      'Yes — a clicked button is never a signature',
      'No — but only because a notary was involved',
    ],
    correct: 1,
    explanation: "E-Sign's core promise is that a contract or signature can't be denied legal effect just because it's electronic; a clicked 'I agree' adopted with intent to sign binds. Paper is not required, and no notary is needed.",
    difficulty: 'application',
    source: 'reader: E-Sign Act · what counts as a signature now',
  },
  {
    id: 'e-sign-act-x05',
    unitId: 'e-sign-act',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: "After a borrower consents to electronic records, the lender changes its software requirements enough that the borrower may no longer be able to open the documents. What right does E-Sign give the borrower?",
    options: [
      'A right to a lower interest rate',
      'A right to withdraw consent free of any fee or penalty',
      'A right to cancel the loan entirely',
      'A right to have the documents re-notarized',
    ],
    correct: 1,
    explanation: "If the hardware or software requirements change enough to risk the consumer no longer being able to open their records, the lender must send a revised statement and give the consumer the right to withdraw consent free of any fee or penalty. It does not entitle the borrower to a rate change or loan cancellation.",
    difficulty: 'analysis',
    source: 'reader: E-Sign Act · when the tech changes, and keeping the records',
  },
  {
    id: 'e-sign-act-x06',
    unitId: 'e-sign-act',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: "A closing is handled entirely on screens, with no paper anywhere. What is the E-Sign Act's core effect that makes this possible?",
    options: [
      'It bans electronic contracts unless notarized',
      'It gives electronic records and signatures the same legal force as paper',
      'It requires every loan to be re-signed on paper within a year',
      'It sets caps on mortgage interest rates',
    ],
    correct: 1,
    explanation: "The E-Sign Act gives electronic records and electronic signatures the same legal force as paper ones, so a mortgage can be signed and delivered entirely on a screen. It does not ban electronic contracts, require later paper signing, or address interest rates.",
    difficulty: 'recall',
    source: 'reader: E-Sign Act · overview',
  },
];

export default bank;
