import type { ExamItem } from '@/content/exam/types';

const bank: ExamItem[] = [
  {
    id: 'ecoa-x01',
    unitId: 'ecoa',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: 'A prospective borrower calls to ask about a mortgage. The loan officer says, "Honestly, at your age most people don’t bother — you probably wouldn’t qualify," and the caller never applies. Has ECOA been violated even though no application exists?',
    options: [
      'No — ECOA only applies once a completed application is on file',
      'No — a violation requires an actual denial of credit',
      'Yes — discouraging a reasonable person from applying on a prohibited basis is itself a violation',
      'Yes, but only if the caller can prove they would have qualified',
    ],
    correct: 2,
    explanation: 'ECOA’s protection reaches before any application exists: it is a violation to discourage a reasonable person from applying on a prohibited basis such as age. No completed application and no formal denial are needed — the discouragement itself breaks the law, regardless of whether the caller would ultimately have qualified.',
    difficulty: 'recall',
    source: 'reader: ECOA · intro (discouragement)',
  },
  {
    id: 'ecoa-x02',
    unitId: 'ecoa',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: 'A borrower submits a completed credit application. By when must the creditor deliver the Notice of Action Taken?',
    options: [
      'Within 30 calendar days',
      'Within 60 calendar days',
      'Within 90 calendar days',
      'Within 3 business days',
    ],
    correct: 0,
    explanation: 'Once an application is complete, the Notice of Action Taken must arrive within 30 calendar days. 60 days is the applicant’s window to submit a written request for the specific reasons behind an adverse decision; 90 days is the time to accept a counteroffer; neither is the notification deadline.',
    difficulty: 'recall',
    source: 'reader: ECOA · the paperwork trail',
  },
  {
    id: 'ecoa-x03',
    unitId: 'ecoa',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: 'A borrower applies by phone and declines to state his race, national origin, and sex when asked for government-monitoring purposes. How must the MLO record the demographic data?',
    options: [
      'Estimate the applicant’s race and sex based on visual observation',
      'Record the refusal and make no designation',
      'Guess based on the applicant’s name and address',
      'Deny the application for failure to provide required information',
    ],
    correct: 1,
    explanation: 'In a non-face-to-face application — phone, mail, or online — a refusal is simply recorded as a refusal, and the MLO may not guess. Visual observation is required only in a face-to-face application where the applicant can be seen. The MLO can never guess from a name, and the refusal is not grounds for denial.',
    difficulty: 'application',
    source: 'reader: ECOA · government monitoring',
  },
  {
    id: 'ecoa-x04',
    unitId: 'ecoa',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: 'An applicant relies on court-ordered child support she is legally entitled to receive. How must the creditor treat that income under ECOA?',
    options: [
      'It must be excluded, because it does not come from employment',
      'It may be counted to the extent it is likely to be consistently received',
      'It must be discounted by half, since support payments are unreliable',
      'It may be considered only if a co-applicant is added',
    ],
    correct: 1,
    explanation: 'A creditor may consider alimony, child support, or separate maintenance payments as income to the extent they are likely to be consistently received — it cannot dismiss the income because of its source. Excluding it outright, applying an automatic discount, or conditioning it on a co-applicant all violate ECOA; a creditor can never require a co-applicant.',
    difficulty: 'application',
    source: 'reader: ECOA · income and co-applicants',
  },
  {
    id: 'ecoa-x05',
    unitId: 'ecoa',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: 'A creditor cannot approve a loan as submitted but offers the applicant different terms. The counteroffer is stated on the Adverse Action Notice. How long does the applicant have to accept it?',
    options: [
      '30 calendar days',
      '60 calendar days',
      '90 calendar days',
      '120 calendar days',
    ],
    correct: 2,
    explanation: 'When a counteroffer appears on the notice, the applicant has 90 calendar days to accept. 60 days is the deadline for the applicant to request the specific reasons for an adverse action; 30 days is the creditor’s window to notify or to respond to a reasons request — not the counteroffer acceptance period.',
    difficulty: 'application',
    source: 'reader: ECOA · the paperwork trail',
  },
  {
    id: 'ecoa-x06',
    unitId: 'ecoa',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: 'A bank decides on pure cost grounds to open only partial-service branches across a metro area, with no intent tied to race. The result is that a predominantly African-American population loses access to full financial services. What kind of discrimination is this?',
    options: [
      'Disparate treatment, because a protected class was harmed',
      'Disparate impact, because a facially neutral policy disproportionately harmed a protected class',
      'No discrimination, because the decision was based on cost',
      'Redlining, because the bank refused to lend in the area',
    ],
    correct: 1,
    explanation: 'This mirrors the Centier Bank case: a facially neutral, cost-driven business decision that disproportionately harmed a protected class is disparate impact. Disparate treatment requires intent to discriminate, which is absent here. A legitimate cost rationale does not cure a discriminatory effect, and the bank did not refuse to lend outright, so it is impact rather than classic redlining.',
    difficulty: 'analysis',
    source: 'reader: ECOA · disparate treatment and disparate impact',
  },
];

export default bank;
