import type { ExamItem } from '@/content/exam/types';

const bank: ExamItem[] = [
  {
    id: 'facta-x01',
    unitId: 'facta',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: 'A consumer files an identity-theft report and places an extended fraud alert on her file. How long does that alert last?',
    options: [
      '1 year',
      '7 years',
      '90 days',
      '2 years',
    ],
    correct: 1,
    explanation: 'An extended fraud alert requires the consumer to file an identity-theft report first, and in exchange it runs for 7 years (it also keeps her off prescreened-offer lists for 5 years and provides two free reports over the next 12 months). The 1-year length is the initial fraud alert, which needs only a good-faith suspicion. The 2-year figure is how long an active-duty alert removes a service member from prescreened lists.',
    difficulty: 'recall',
    source: 'reader: FACTA · fraud alerts',
  },
  {
    id: 'facta-x02',
    unitId: 'facta',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: 'Under the FTC Disposal Rule, which method of destroying a consumer’s personal information is compliant?',
    options: [
      'Shredding the documents',
      'Dropping them intact in a locked recycling bin',
      'Storing them in an off-site archive',
      'Deleting the electronic index that points to them',
    ],
    correct: 0,
    explanation: 'The Disposal Rule allows only three ways to destroy consumer information: shredding, burning, or pulverizing. Tossing sensitive documents intact — even into a locked bin — is a violation, as is merely archiving them or deleting an index while the records survive.',
    difficulty: 'recall',
    source: 'reader: FACTA · the disposal rule',
  },
  {
    id: 'facta-x03',
    unitId: 'facta',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: 'A borrower submits a mortgage application. Within what timeframe must the lender send the Credit Score Disclosure telling him the score it used?',
    options: [
      'Within 3 business days of the application',
      'Within 30 days of the application',
      'Within 24 hours of pulling the report',
      'At closing, with the other final disclosures',
    ],
    correct: 0,
    explanation: 'On a mortgage, FACTA requires the lender to send the Credit Score Disclosure within 3 business days of the application. Thirty days, 24 hours, and delivery at closing are not the FACTA timing for this disclosure.',
    difficulty: 'application',
    source: 'reader: FACTA · free reports and fast disclosures',
  },
  {
    id: 'facta-x04',
    unitId: 'facta',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: 'A service member deploying overseas wants a flag that tells lenders to verify identity before extending credit in her absence. She places an active-duty alert. What does it provide?',
    options: [
      'It lasts 7 years and requires an identity-theft report',
      'It lasts at least 12 months and keeps her off prescreened credit and insurance lists for two years',
      'It lasts 90 days and cannot be renewed',
      'It permanently freezes her credit file',
    ],
    correct: 1,
    explanation: 'An active-duty alert lasts at least 12 months and keeps the service member off prescreened credit and insurance lists for two years. The 7-year length with an identity-theft report describes an extended fraud alert, not an active-duty alert. An active-duty alert is not a 90-day flag and does not permanently freeze the file.',
    difficulty: 'application',
    source: 'reader: FACTA · active-duty alerts',
  },
  {
    id: 'facta-x05',
    unitId: 'facta',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: 'A credit report comes back with an address that does not match the one the applicant provided. What must the lender do before relying on the report?',
    options: [
      'Deny the application automatically as suspected fraud',
      'Form a reasonable belief that the report actually belongs to the applicant',
      'Report the discrepancy to law enforcement within 24 hours',
      'Ignore the mismatch if the credit score is high enough',
    ],
    correct: 1,
    explanation: 'When a report comes back with an address discrepancy, the lender must form a reasonable belief that the report actually belongs to the person in front of it before relying on it. It is not required to deny automatically or to report to law enforcement, and a high score never excuses ignoring the mismatch.',
    difficulty: 'application',
    source: 'reader: FACTA · address changes and discrepancies',
  },
  {
    id: 'facta-x06',
    unitId: 'facta',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: 'A consumer suspects she may have been targeted by fraud but has not filed any police or identity-theft report. Which alert can she place, and for how long?',
    options: [
      'An extended fraud alert, lasting 7 years',
      'An initial fraud alert, lasting at least 1 year',
      'No alert is available without a filed report',
      'An active-duty alert, lasting 12 months',
    ],
    correct: 1,
    explanation: 'An initial fraud alert can be placed on a good-faith suspicion of being victimized and lasts at least 1 year — no identity-theft report is required. An extended alert is the one that requires a filed identity-theft report (and runs 7 years). An active-duty alert is for deployed service members, not this situation.',
    difficulty: 'analysis',
    source: 'reader: FACTA · fraud alerts',
  },
];

export default bank;
