import type { ExamItem } from '@/content/exam/types';

const bank: ExamItem[] = [
  {
    id: 'fcra-x01',
    unitId: 'fcra',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: 'A borrower asks which single factor moves her credit score the most. What is the correct answer?',
    options: [
      'Amounts owed, at 30%',
      'Payment history, at 35%',
      'Length of credit history, at 15%',
      'New credit, at 10%',
    ],
    correct: 1,
    explanation: 'Payment history — whether you pay on time — is the biggest factor at 35%. Amounts owed is next at 30%, then length of history at 15%, credit mix at 10%, and new credit at 10%. So payment history, not amounts owed, is the largest single driver.',
    difficulty: 'recall',
    source: 'reader: FCRA · the score',
  },
  {
    id: 'fcra-x02',
    unitId: 'fcra',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: 'A borrower filed Chapter 7 bankruptcy. How long can it be reported on his credit file?',
    options: [
      '7 years',
      '10 years',
      '3 years',
      'Indefinitely',
    ],
    correct: 1,
    explanation: 'A Chapter 7 bankruptcy reports for 10 years — one of the heavier marks. Most negatives, including late payments, collections, charge-offs, foreclosures, and a Chapter 13 bankruptcy, fall off after 7 years. Only an unpaid tax lien can be reported potentially forever.',
    difficulty: 'recall',
    source: 'reader: FCRA · how long marks last',
  },
  {
    id: 'fcra-x03',
    unitId: 'fcra',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: 'A loan officer is curious about a neighbor’s finances and wants to pull the neighbor’s credit report, though the neighbor has no dealings with the lender. Is that permitted under FCRA?',
    options: [
      'Yes — a licensed loan officer may pull any report',
      'No — a user needs both the consumer’s permission and a permissible purpose',
      'Yes, as long as the officer does not share the report',
      'No — but only because the neighbor did not sign a tri-merge authorization',
    ],
    correct: 1,
    explanation: 'A user may pull a file only with both permission from the consumer and a permissible purpose, such as reviewing that consumer’s loan application. Idle curiosity is neither. A license does not confer access, and not sharing the report does not cure the lack of a permissible purpose or consent.',
    difficulty: 'application',
    source: 'reader: FCRA · who’s allowed to look',
  },
  {
    id: 'fcra-x04',
    unitId: 'fcra',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: 'After reviewing the credit report with a borrower, the loan officer is asked to just print the borrower a copy of it. May the officer hand it over?',
    options: [
      'Yes — the borrower is entitled to a copy from anyone who has it',
      'No — only a credit bureau or credit repository may give the consumer a copy',
      'Yes, but only once per year',
      'No — the borrower must file a dispute to see the report',
    ],
    correct: 1,
    explanation: 'A lender can go over the report with the borrower but cannot hand over a copy — only a bureau or credit repository can provide that. The once-a-year free report and the dispute process are separate mechanisms and do not change who may physically supply the copy.',
    difficulty: 'application',
    source: 'reader: FCRA · who’s allowed to look',
  },
  {
    id: 'fcra-x05',
    unitId: 'fcra',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: 'A rapid rescore corrects an error and lifts a borrower’s score so a pending loan can close. Is the error now fixed permanently?',
    options: [
      'Yes — a rapid rescore permanently updates all three bureaus',
      'No — it only fixes the file for the current transaction; a direct dispute is still needed to clear it for good',
      'Yes — but only if a tri-merge report was ordered',
      'No — the error can never be permanently removed',
    ],
    correct: 1,
    explanation: 'Tools ordered through the repository — tradeline verification, an investigative consumer report, and a rapid rescore — only fix the file for the current transaction. To clear an error for good, the borrower still has to take it up with the furnisher or the bureau directly through a dispute. Errors can be permanently corrected; it just takes the direct route, not a rapid rescore.',
    difficulty: 'application',
    source: 'reader: FCRA · the quick fix versus the real fix',
  },
  {
    id: 'fcra-x06',
    unitId: 'fcra',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: 'A borrower’s report shows several old derogatory items. Which of these can remain on the report indefinitely rather than aging off?',
    options: [
      'A foreclosure',
      'A Chapter 7 bankruptcy',
      'An unpaid tax lien',
      'A collection account',
    ],
    correct: 2,
    explanation: 'An unpaid tax lien is the one item that never expires on its own — it can be reported potentially forever. A foreclosure and a collection age off after 7 years, and a Chapter 7 bankruptcy after 10 years. Only the unpaid lien has no expiration.',
    difficulty: 'analysis',
    source: 'reader: FCRA · how long marks last',
  },
];

export default bank;
