import type { ExamItem } from '@/content/exam/types';

const bank: ExamItem[] = [
  {
    id: 'fha-x01',
    unitId: 'fha',
    moduleId: 'general-mortgage-knowledge',
    area: 'general',
    pool: 'section',
    stem: "A buyer with a modest down payment and a lower credit score than a conventional loan would accept is approved for an FHA loan. What federal agency's backing makes that possible?",
    options: [
      'The loan is guaranteed by the VA',
      'The loan is insured by HUD',
      'The loan is guaranteed by the USDA',
      'The loan is bought by Fannie Mae and Freddie Mac',
    ],
    correct: 1,
    explanation: 'An FHA loan is insured by HUD, so a borrower can qualify with a smaller down payment and a lower credit score than a conventional loan requires. VA and USDA guarantee rather than insure; conventional loans are bought by Fannie and Freddie.',
    difficulty: 'recall',
    source: 'reader: FHA · structuring an FHA loan',
  },
  {
    id: 'fha-x02',
    unitId: 'fha',
    moduleId: 'general-mortgage-knowledge',
    area: 'general',
    pool: 'section',
    stem: "An FHA borrower asks how the mortgage insurance on their loan is charged. Which description is correct?",
    options: [
      'A single premium paid entirely at closing',
      'Two parts — an up-front premium and an annual premium collected monthly',
      'A premium charged only until the loan reaches 80% LTV',
      'A premium that replaces the borrower\'s homeowner\'s insurance',
    ],
    correct: 1,
    explanation: "FHA mortgage insurance comes in two parts: an up-front premium (usually financed into the loan) and an annual premium collected monthly inside the payment. It doesn't replace homeowner's insurance, and it isn't a one-time closing charge.",
    difficulty: 'recall',
    source: 'reader: FHA · structuring an FHA loan',
  },
  {
    id: 'fha-x03',
    unitId: 'fha',
    moduleId: 'general-mortgage-knowledge',
    area: 'general',
    pool: 'section',
    stem: "A borrower's base loan amount is $300,000 and their FHA loan closes at a slightly higher figure than that. What most likely accounts for the difference?",
    options: [
      'The annual MIP was added to the loan',
      'The up-front MIP (1.75% of the base loan amount) was financed into the loan',
      'The lender rounded the loan up to the nearest $50',
      'Property taxes were rolled into the principal',
    ],
    correct: 1,
    explanation: 'The up-front MIP is 1.75% of the base loan amount, and most borrowers finance it into the loan rather than pay it at closing — so the loan is the base plus the UFMIP (then rounded down to the nearest $50). The annual MIP rides inside the monthly payment, not the loan balance.',
    difficulty: 'application',
    source: 'reader: FHA · structuring an FHA loan',
  },
  {
    id: 'fha-x04',
    unitId: 'fha',
    moduleId: 'general-mortgage-knowledge',
    area: 'general',
    pool: 'section',
    stem: "An FHA borrower wants to avoid a large cash outlay at closing. What does the reader say most borrowers do with the up-front MIP?",
    options: [
      'Pay it in full at closing to lower the rate',
      'Finance it into the loan and repay it over the term',
      'Split it across the first year of payments',
      'Have the seller pay it as a concession',
    ],
    correct: 1,
    explanation: 'Most borrowers finance the up-front MIP into the loan rather than pay it at closing, which spares them a large cash outlay — the premium is rolled into the loan amount and repaid over the term.',
    difficulty: 'application',
    source: 'reader: FHA · why finance the up-front MIP',
  },
  {
    id: 'fha-x05',
    unitId: 'fha',
    moduleId: 'general-mortgage-knowledge',
    area: 'general',
    pool: 'section',
    stem: "On an FHA loan, a borrower's full monthly payment is described as PITI. Where does the monthly MIP show up?",
    options: [
      'It is billed separately once a year',
      'It rides inside the PITI payment',
      'It is added to the principal balance each month',
      'It is paid only at the up-front stage, so it is not monthly',
    ],
    correct: 1,
    explanation: 'PITI is principal, interest, taxes, and insurance — the full monthly payment. On an FHA loan the monthly (annual) MIP rides inside it, collected with each payment rather than billed separately.',
    difficulty: 'application',
    source: 'reader: FHA · PITI',
  },
  {
    id: 'fha-x06',
    unitId: 'fha',
    moduleId: 'general-mortgage-knowledge',
    area: 'general',
    pool: 'section',
    stem: "Two figures on the FHA worksheet sound similar: the up-front MIP and the annual MIP. Which pair correctly describes how each is set and collected?",
    options: [
      'Both are 1.75% and both are collected monthly',
      'Up-front MIP is 1.75% of the base loan amount (one-time); annual MIP is set by loan term and LTV and collected monthly',
      'Up-front MIP is set by loan term and LTV; annual MIP is a flat 1.75%',
      'Both are set by loan term and LTV and paid once at closing',
    ],
    correct: 1,
    explanation: 'The up-front MIP (UFMIP) is a one-time 1.75% of the base loan amount. The annual MIP (AMIP) is set by loan term and loan-to-value and collected monthly inside the payment. Confusing which figure is fixed at 1.75% is the common trap.',
    difficulty: 'analysis',
    source: 'reader: FHA · up-front MIP vs annual MIP',
  },
];

export default bank;
