import type { ExamItem } from '@/content/exam/types';

const bank: ExamItem[] = [
  {
    id: 'ftc-red-flags-rule-x01',
    unitId: 'ftc-red-flags-rule',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: 'FACTA’s fraud alerts put tools in the consumer’s hands. By contrast, whom does the FTC Red Flags Rule put on the hook to actively watch for identity theft before an account is opened or funded?',
    options: [
      'The consumer, who must monitor their own file',
      'The business — every creditor under FTC enforcement, including mortgage lenders and brokers',
      'The credit bureaus alone',
      'Federal law enforcement',
    ],
    correct: 1,
    explanation: 'The Red Flags Rule flips the burden onto the business: a lender must actively watch for identity theft before it opens or funds an account. It applies to every creditor under FTC enforcement, which includes mortgage lenders and brokers. Consumer-facing tools like fraud alerts are FACTA’s side; here the duty is the creditor’s.',
    difficulty: 'recall',
    source: 'reader: FTC Red Flags Rule · intro',
  },
  {
    id: 'ftc-red-flags-rule-x02',
    unitId: 'ftc-red-flags-rule',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: 'A creditor’s Identity Theft Prevention Program must answer to leadership. How often must it report to the board or senior management?',
    options: [
      'At least annually',
      'At least quarterly',
      'Only when a red flag is detected',
      'Every five years',
    ],
    correct: 0,
    explanation: 'The program has to answer to leadership by reporting to the board or senior management at least annually. Quarterly reporting, event-triggered reporting, and a five-year cycle are not what the rule requires.',
    difficulty: 'recall',
    source: 'reader: FTC Red Flags Rule · the identity-theft prevention program',
  },
  {
    id: 'ftc-red-flags-rule-x03',
    unitId: 'ftc-red-flags-rule',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: 'The Red Flags Rule attaches to a "covered account." Which of these fits that definition?',
    options: [
      'A one-time, single-payment cash transaction',
      'A mortgage — a personal, family, or household account allowing multiple payments over time',
      'A business line extended to a corporation',
      'A brokerage account holding securities',
    ],
    correct: 1,
    explanation: 'A covered account is one a creditor offers mainly for personal, family, or household purposes that allows multiple payments or transactions — a mortgage is the textbook case. The multiple-payment feature is what makes an account a standing target for impersonation over time, so a one-off transaction does not qualify, and business/securities accounts are outside this consumer-account definition.',
    difficulty: 'application',
    source: 'reader: FTC Red Flags Rule · covered accounts',
  },
  {
    id: 'ftc-red-flags-rule-x04',
    unitId: 'ftc-red-flags-rule',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: 'A compliance officer is building the written Identity Theft Prevention Program. Which set of ongoing jobs must it perform?',
    options: [
      'Insure, disclose, rescind, and audit',
      'Identify, detect, respond, and update',
      'Collect, report, retain, and certify',
      'Underwrite, fund, service, and transfer',
    ],
    correct: 1,
    explanation: 'The program is a standing routine that must do four things and keep doing them: identify the red flags relevant to its accounts, detect them in day-to-day business, respond appropriately when one appears, and stay updated as new theft patterns emerge. The other lists describe unrelated functions.',
    difficulty: 'application',
    source: 'reader: FTC Red Flags Rule · the identity-theft prevention program',
  },
  {
    id: 'ftc-red-flags-rule-x05',
    unitId: 'ftc-red-flags-rule',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: 'A creditor hires an outside service provider to work on its covered accounts. What is the creditor’s responsibility for that provider under the Red Flags Rule?',
    options: [
      'None — responsibility ends at the creditor’s own door',
      'It must make sure the provider follows red-flag procedures and can be held liable if the provider’s controls fall short',
      'It must only keep a copy of the provider’s contract on file',
      'It must file the provider’s program with the FTC each year',
    ],
    correct: 1,
    explanation: 'Responsibility doesn’t end at the company’s door: when a creditor hires a service provider to work on covered accounts, it must ensure that provider follows red-flag procedures too, and it can be held liable for harm to its customers if the provider’s controls fall short. Merely keeping a contract or filing paperwork with the FTC does not satisfy the duty.',
    difficulty: 'application',
    source: 'reader: FTC Red Flags Rule · the guidelines and service providers',
  },
  {
    id: 'ftc-red-flags-rule-x06',
    unitId: 'ftc-red-flags-rule',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: 'During processing, staff notice the applicant’s documents appear altered and the Social Security number he gave belongs to someone else. Under the Red Flags Rule, how should this be treated?',
    options: [
      'It is not a red flag unless a credit bureau also sends an alert',
      'These are red flags — suspicious documents and suspicious personal information — that the program must detect and respond to',
      'It is only a concern after the loan closes',
      'It can be ignored if the applicant otherwise qualifies',
    ],
    correct: 1,
    explanation: 'Altered-looking documents and a Social Security number that belongs to someone else are exactly the red flags the Guidelines describe — suspicious documents and suspicious personal information — each signaling possible impersonation. The rule expects staff to recognize these and respond; a credit-bureau alert is only one example among several, and the whole point is to act before the account is opened or funded, not after.',
    difficulty: 'analysis',
    source: 'reader: FTC Red Flags Rule · what a red flag looks like',
  },
];

export default bank;
