import type { ExamItem } from '@/content/exam/types';

const bank: ExamItem[] = [
  {
    id: 'getting-licensed-x01',
    unitId: 'getting-licensed',
    moduleId: 'uniform-state-content',
    area: 'ust',
    pool: 'section',
    stem: "A candidate is about to apply and realizes he submitted his fingerprints for the FBI check 200 days ago. What does that mean for his background check?",
    options: [
      'They are too old — prints must be obtained within the most-recent 180 days',
      'They are fine — fingerprints are valid for 3 years',
      'They never expire once submitted',
      'They must be resubmitted to the CFPB, not the FBI',
    ],
    correct: 0,
    explanation: 'Before applying, a candidate submits fingerprints for a state and national criminal-history check run through the FBI, obtained within the most-recent 180 days. At 200 days they are stale and must be retaken.',
    difficulty: 'recall',
    source: 'reader: getting licensed · the background check',
  },
  {
    id: 'getting-licensed-x02',
    unitId: 'getting-licensed',
    moduleId: 'uniform-state-content',
    area: 'ust',
    pool: 'section',
    stem: "A candidate is filling out form MU4 and reaches the personal-history section. What history must she provide?",
    options: [
      'Only the past 3 years of addresses',
      'The most-recent 10 years of residential and employment history, with no gaps',
      'The past 7 years of employment only',
      'Her entire lifetime employment record',
    ],
    correct: 1,
    explanation: 'The candidate files a full personal history: the most-recent 10 years of residential and employment history, containing no gaps, plus any past administrative, civil, or criminal findings, all submitted on form MU4.',
    difficulty: 'recall',
    source: 'reader: getting licensed · the background check',
  },
  {
    id: 'getting-licensed-x03',
    unitId: 'getting-licensed',
    moduleId: 'uniform-state-content',
    area: 'ust',
    pool: 'section',
    stem: "A candidate was convicted 12 years ago of a felony involving money laundering. How does that affect his eligibility for an MLO license?",
    options: [
      'It no longer matters — it falls outside the 7-year window',
      "It's cleared once 10 years have passed",
      'It permanently disqualifies him — fraud and money-laundering felonies have no time limit',
      'It matters only if it was a federal charge',
    ],
    correct: 2,
    explanation: 'An ordinary felony disqualifies only within the past 7 years, but a felony involving fraud, dishonesty, a breach of trust, or money laundering disqualifies the candidate ever, with no time limit at all.',
    difficulty: 'application',
    source: 'reader: getting licensed · the minimum standards',
  },
  {
    id: 'getting-licensed-x04',
    unitId: 'getting-licensed',
    moduleId: 'uniform-state-content',
    area: 'ust',
    pool: 'section',
    stem: "A fully qualified candidate submits her application but has no employer lined up to sponsor her. What does the state do?",
    options: [
      "Issues the license as 'approved-inactive'; she cannot originate until sponsorship makes it active",
      'Denies the application outright for lack of an employer',
      'Issues a fully active license immediately',
      'Requires her to retake the national exam first',
    ],
    correct: 0,
    explanation: "Submit without a sponsor and, if otherwise qualified, the state issues the license in 'approved-inactive' status. No loan can be originated until a sponsorship flips it to 'approved-active.'",
    difficulty: 'application',
    source: 'reader: getting licensed · sponsorship',
  },
  {
    id: 'getting-licensed-x05',
    unitId: 'getting-licensed',
    moduleId: 'uniform-state-content',
    area: 'ust',
    pool: 'section',
    stem: "An MLO candidate has just failed the national exam on his second attempt. When can he try for the third time?",
    options: [
      'Immediately — there is no waiting period',
      'At least 30 days after the second attempt',
      'Only after a 6-month wait',
      'Never — two failures ends his eligibility',
    ],
    correct: 1,
    explanation: 'A candidate gets three attempts in all, with each try at least 30 days after the last. The 6-month lockout only applies after failing all three.',
    difficulty: 'application',
    source: 'reader: getting licensed · the exam',
  },
  {
    id: 'getting-licensed-x06',
    unitId: 'getting-licensed',
    moduleId: 'uniform-state-content',
    area: 'ust',
    pool: 'section',
    stem: "A provider is building the minimum NMLS-approved pre-licensing course. Which allocation meets the SAFE Act minimums?",
    options: [
      '8 total hours, including 3 hours of federal law',
      '20 total hours, all of them federal law',
      '20 total hours, including at least 3 hours of federal law, 3 hours of ethics, and 2 hours on non-traditional mortgage products',
      '12 total hours, including 2 hours of ethics',
    ],
    correct: 2,
    explanation: 'Pre-licensing education is at least 20 NMLS-approved hours, carved into at least 3 hours of federal law, 3 hours of ethics, and 2 hours on non-traditional mortgage products, with the rest rounding out the 20. (8 total hours is the annual continuing-education figure.)',
    difficulty: 'analysis',
    source: 'reader: getting licensed · pre-licensing education',
  },
];

export default bank;
