import type { ExamItem } from '@/content/exam/types';

const bank: ExamItem[] = [
  {
    id: 'glba-x01',
    unitId: 'glba',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: "A borrower notices that the same corporate family holds her checking account, her brokerage, and her homeowners insurance. She asks how that combination became legal. Which repeal made it possible?",
    options: [
      'The repeal of Glass-Steagall (1933)',
      'The repeal of the Bank Secrecy Act',
      'The repeal of the Truth in Lending Act',
      'The repeal of the Homeowners Protection Act',
    ],
    correct: 0,
    explanation: "GLBA tore down the Glass-Steagall wall that had kept banking, investing, and insurance in separate companies, letting them combine into financial holding companies. That concentration is exactly the privacy risk GLBA was written to manage.",
    difficulty: 'recall',
    source: 'reader: GLBA · why bank mergers created a privacy problem',
  },
  {
    id: 'glba-x02',
    unitId: 'glba',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: "A person calls a lender, gets a rate quote, and never opens an account or takes a loan. Under GLBA, is that person owed the privacy notice on a repeating, annual basis?",
    options: [
      'Yes — everyone who contacts a lender is owed the notice yearly',
      'No — as a one-time consumer, they are not owed the repeated notice a customer gets',
      'Yes — but only if they ask for it in writing',
      'No — quotes are exempt from GLBA entirely',
    ],
    correct: 1,
    explanation: "A one-time consumer has no continuing relationship, so they are not owed the repeated privacy notice. A customer — someone who opened an account or took a loan — gets the notice up front and on a repeating basis. GLBA still covers the consumer's information; it just does not require the recurring notice.",
    difficulty: 'application',
    source: 'reader: GLBA · consumer versus customer',
  },
  {
    id: 'glba-x03',
    unitId: 'glba',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: "A lender wants to give a customer's account number to an outside company so that company can run its own telemarketing campaign. Does GLBA allow this?",
    options: [
      'Yes, as long as the customer was given a chance to opt out',
      'Yes, if it is done under a joint marketing agreement',
      'Never — account numbers may not go to a nonaffiliated third party for its marketing',
      'Yes, if the customer previously received a privacy notice',
    ],
    correct: 2,
    explanation: "GLBA flatly bars handing a customer's account number to an outside company for that company's telemarketing or mail marketing — there is no opt-out or joint-marketing path around it. Opt-out and joint-marketing exceptions apply to other NPI sharing, not to account numbers for marketing.",
    difficulty: 'application',
    source: 'reader: GLBA · the deal: notice and opt-out',
  },
  {
    id: 'glba-x04',
    unitId: 'glba',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: "A compliance officer is sorting borrower details into 'protected NPI' and 'not protected.' Which item is nonpublic personal information GLBA protects?",
    options: [
      "The borrower's loan application and account balance",
      "The borrower's address as listed in public property records",
      'Information available through a Freedom of Information Act request',
      'A record found through a general public records search',
    ],
    correct: 0,
    explanation: "NPI is financial information about a person that could not be dug up through a public records search or a FOIA request — a loan application and account balance qualify. Anything already public, like property-record data or FOIA-available information, is not protected NPI.",
    difficulty: 'application',
    source: 'reader: GLBA · what NPI is',
  },
  {
    id: 'glba-x05',
    unitId: 'glba',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: "An examiner asks a mortgage company to demonstrate how it complies with GLBA's Safeguards Rule. What must the company be able to show it has built?",
    options: [
      'A written information security program with administrative, technical, and physical safeguards',
      'A fixed-rate guarantee on every loan it originates',
      'An annual credit report pulled on each customer',
      'A co-signer requirement for low-equity borrowers',
    ],
    correct: 0,
    explanation: "The Safeguards Rule requires a written information security program — real administrative, technical, and physical protections, with a qualified individual to run it, risk assessments, access controls, testing, training, and service-provider oversight. The other options have nothing to do with securing customer data.",
    difficulty: 'recall',
    source: 'reader: GLBA · the Safeguards Rule',
  },
  {
    id: 'glba-x06',
    unitId: 'glba',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: "A regulator finds a GLBA violation and names an individual officer of the institution as personally liable. What is the maximum fine that officer faces per the unit?",
    options: [
      '$2,000',
      '$10,000',
      '$25,000',
      '$100,000',
    ],
    correct: 1,
    explanation: "GLBA caps fines on officers and directors at up to $10,000 each (with up to five years' imprisonment). The $100,000 figure is the per-violation cap on the institution itself, not on an individual officer.",
    difficulty: 'analysis',
    source: 'reader: GLBA · what non-compliance costs',
  },
];

export default bank;
