import type { ExamItem } from '@/content/exam/types';

const bank: ExamItem[] = [
  {
    id: 'hmda-x01',
    unitId: 'hmda',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: 'A regulator sifts a lender’s reported data and finds it has systematically avoided lending in poor, majority-minority neighborhoods regardless of individual qualifications. Which practice is HMDA chiefly built to expose?',
    options: [
      'Usury',
      'Redlining',
      'Appraisal fraud',
      'Money laundering',
    ],
    correct: 1,
    explanation: 'HMDA forces the pattern of lending into the open so regulators can catch redlining — an institution avoiding whole areas and starving them of mortgages. One loan decision looks innocent; the aggregate data is where the discrimination shows. Usury, appraisal fraud, and money laundering are addressed by other laws, not HMDA’s reporting scheme.',
    difficulty: 'recall',
    source: 'reader: HMDA · redlining, and why lending got mapped',
  },
  {
    id: 'hmda-x02',
    unitId: 'hmda',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: 'The Loan/Application Register carries many data points. Which single piece is the loan originator personally responsible for collecting?',
    options: [
      'The loan amount and purpose',
      'The applicant’s race, national origin, and sex',
      'The property’s appraised value',
      'The final disposition of the application',
    ],
    correct: 1,
    explanation: 'Of everything on the LAR, the loan originator is personally responsible for collecting one piece: the applicant’s race, national origin, and sex. The loan amount, property value, and disposition are all reported, but they are not the data point the originator is personally charged with gathering.',
    difficulty: 'recall',
    source: 'reader: HMDA · the register',
  },
  {
    id: 'hmda-x03',
    unitId: 'hmda',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: 'A lender has an office in a metropolitan area, meets the asset threshold, and originated 30 closed-end mortgages in each of the two prior years. Must it report its closed-end lending under HMDA?',
    options: [
      'No — it must originate at least 200 loans to be covered',
      'Yes — it crossed the closed-end line of at least 25 in each of the two prior years',
      'No — only depository banks report under HMDA',
      'Yes, but only if it also made 200 open-end lines of credit',
    ],
    correct: 1,
    explanation: 'A covered lender must have originated at least 25 closed-end mortgage loans in each of the two prior years (or at least 200 open-end lines of credit). With an MSA office, the asset test met, and 30 closed-end loans each year, this lender crosses the closed-end line. The 200 count is the separate open-end threshold, not a requirement on top of the closed-end one, and non-depository lenders can be covered too.',
    difficulty: 'application',
    source: 'reader: HMDA · who has to report',
  },
  {
    id: 'hmda-x04',
    unitId: 'hmda',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: 'A covered lender makes a loan secured by unimproved land. Is that loan reportable on the LAR?',
    options: [
      'Yes — all dwelling-secured loans are reportable',
      'No — loans on unimproved land are carved out of HMDA reporting',
      'Yes, but only if it exceeds $500',
      'No — but only because unimproved land is never in an MSA',
    ],
    correct: 1,
    explanation: 'HMDA carves out loans that say little about community lending, including loans on unimproved land, temporary bridge financing, agricultural or business-purpose loans (unless a home purchase, improvement, or refinance), pool/servicing-right purchases, and any loan under $500. A home improvement loan, by contrast, would be reportable. The $500 floor and MSA location are unrelated to the unimproved-land exclusion.',
    difficulty: 'application',
    source: 'reader: HMDA · what’s left out',
  },
  {
    id: 'hmda-x05',
    unitId: 'hmda',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: 'A lender that files HMDA data only once a year is preparing its full prior-year Loan/Application Register. By when must it submit the annual filing?',
    options: [
      'By January 1',
      'By March 1',
      'Within 60 days after year-end',
      'By April 15',
    ],
    correct: 1,
    explanation: 'The annual LAR must be submitted in electronic form, certified accurate by someone who knows the data, by March 1 each year. The 60-day deadline applies only to the largest lenders’ quarterly filings (for quarters one through three), and January 1 and April 15 are not HMDA deadlines.',
    difficulty: 'application',
    source: 'reader: HMDA · when the reports are due',
  },
  {
    id: 'hmda-x06',
    unitId: 'hmda',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: 'A borrower applies by phone and refuses to self-identify race, national origin, and sex, so the MLO records the refusal. Weeks later the borrower comes to the office in person. May the MLO now record the demographics by visual observation?',
    options: [
      'Yes — once they meet face-to-face, visual observation applies',
      'No — for a non-face-to-face application, the refusal stands and may not be changed later',
      'Yes — but only if the borrower still declines to self-identify in person',
      'No — the MLO must instead ask a third party to identify the borrower',
    ],
    correct: 1,
    explanation: 'For a non-face-to-face application, a refusal is noted and the process stops; the MLO may not go back and change what was recorded even after later meeting the applicant or seeing a photo. Visual observation is required only when the application itself is face-to-face, not when a phone applicant happens to visit afterward. Guessing or asking a third party is never permitted.',
    difficulty: 'analysis',
    source: 'reader: HMDA · collecting the demographic data',
  },
];

export default bank;
