import type { ExamItem } from '@/content/exam/types';

const bank: ExamItem[] = [
  {
    id: 'hoepa-x01',
    unitId: 'hoepa',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: 'A first-lien loan on the borrower’s principal dwelling has an APR that sits 6.8 percentage points above the Average Prime Offer Rate. Its points and fees are modest and it has no prepayment penalty. Is it a high-cost loan?',
    options: [
      'No — a loan must cross all three high-cost triggers',
      'Yes — crossing the rate trigger alone (6.5 points over APOR for a first lien) makes it high-cost',
      'No — the first-lien rate trigger is 8.5 points over APOR',
      'Yes, but only because its points and fees are also above 5%',
    ],
    correct: 1,
    explanation: 'A loan becomes high-cost the moment it crosses any one of the three lines — you don’t need all three. A first-lien loan trips the rate trigger at 6.5 percentage points or more over APOR, and 6.8 clears it. 8.5 points is the trigger for a subordinate lien or a small personal-property loan, not a first lien. The points and fees are modest, so that isn’t the trigger here.',
    difficulty: 'recall',
    source: 'reader: HOEPA · the rate trigger',
  },
  {
    id: 'hoepa-x02',
    unitId: 'hoepa',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: 'A lender drafting a loan that qualifies as high-cost wants to include a prepayment penalty. May it?',
    options: [
      'Yes, up to 2% of the amount prepaid',
      'Yes, as long as it can only be charged in the first 36 months',
      'No — a high-cost loan may not carry a prepayment penalty at all',
      'Yes, if the borrower waives the right to prepay',
    ],
    correct: 2,
    explanation: 'Once a loan is high-cost, HOEPA strips out the terms predatory loans rely on, including prepayment penalties — none are allowed. The 2%-of-amount-prepaid and 36-month figures are what turn an ordinary loan into a high-cost one in the first place; they are not a ceiling for penalties inside a loan that is already high-cost.',
    difficulty: 'recall',
    source: 'reader: HOEPA · what high-cost turns off',
  },
  {
    id: 'hoepa-x03',
    unitId: 'hoepa',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: 'On a $300,000 loan, total points and fees come to 5.5% of the loan amount. The rate is ordinary and there is no prepayment penalty. Does the loan become high-cost?',
    options: [
      'No — the points-and-fees trigger is 8% for a loan of this size',
      'Yes — for a loan of $27,592 or more, points and fees over 5% of the loan amount make it high-cost',
      'No — points and fees never trigger high-cost status on their own',
      'Yes — but only because the loan exceeds $27,592 in size',
    ],
    correct: 1,
    explanation: 'On a normal-sized loan ($27,592 or more), the loan goes high-cost once total points and fees exceed 5% of the loan amount, and 5.5% clears that line. The 8% test (as the lesser of 8% or about $1,380) applies to smaller loans. Points and fees are one of the three independent triggers, so they can flip a loan high-cost by themselves; simply being over $27,592 is not the trigger — exceeding 5% is.',
    difficulty: 'application',
    source: 'reader: HOEPA · the points-and-fees trigger',
  },
  {
    id: 'hoepa-x04',
    unitId: 'hoepa',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: 'A borrower is about to take out a high-cost mortgage. What counseling does HOEPA require before the loan can close, and who provides it?',
    options: [
      'Counseling from a HUD-approved counselor the lender assigns and pays',
      'Homeownership counseling from a HUD-approved counselor of the borrower’s own choosing who is not tied to the lender, with the lender holding written certification',
      'No counseling — only a special disclosure three days before closing',
      'Legal counseling from the lender’s attorney',
    ],
    correct: 1,
    explanation: 'The borrower must first get homeownership counseling from a HUD-approved counselor of their own choosing — one not employed by or affiliated with the lender — and the lender must hold written certification before extending the loan. A lender-assigned or lender-affiliated counselor defeats the independence requirement. The special high-cost disclosure (at least 3 business days before consummation) is in addition to the counseling, not a substitute.',
    difficulty: 'application',
    source: 'reader: HOEPA · counseling and the warning',
  },
  {
    id: 'hoepa-x05',
    unitId: 'hoepa',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: 'An elderly homeowner is offered a reverse mortgage on her principal dwelling that carries very high costs. Do HOEPA’s high-cost rules apply to it?',
    options: [
      'Yes — any high-cost loan on a principal dwelling is covered',
      'No — reverse mortgages are excluded from HOEPA coverage',
      'Yes, because the borrower is elderly and the costs are high',
      'No — but only if a state Housing Finance Agency is involved',
    ],
    correct: 1,
    explanation: 'HOEPA reaches consumer loans on a principal dwelling but expressly leaves out reverse mortgages, loans for a home’s initial construction, loans where a state Housing Finance Agency is the creditor, and USDA Section 502 Direct loans. So no matter how high the costs or the borrower’s age, a reverse mortgage is outside HOEPA. The HFA carve-out is a separate exemption, not a condition on the reverse-mortgage one.',
    difficulty: 'application',
    source: 'reader: HOEPA · the three lines that make a loan high-cost',
  },
  {
    id: 'hoepa-x06',
    unitId: 'hoepa',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: 'A lender writes a fee-heavy loan with a payment it knows the borrower cannot sustain, expecting the borrower to default so the lender can foreclose. What is this abuse, and what is HOEPA guarding against?',
    options: [
      'Steering — HOEPA is protecting the borrower’s interest rate',
      'Equity stripping — HOEPA is protecting the equity the borrower has built in the home',
      'Redlining — HOEPA is protecting neighborhood access to credit',
      'Loan flipping — HOEPA is protecting the borrower’s credit score',
    ],
    correct: 1,
    explanation: 'This is equity stripping: the lender loads the loan with fees and an unaffordable payment expecting default, then forecloses and takes a home that had real equity in it — the foreclosure is the goal, not a failure. HOEPA is named against exactly this, protecting the borrower’s equity. Steering and redlining are other laws’ concerns; the harm here is loss of equity, not the rate, neighborhood access, or a credit score.',
    difficulty: 'analysis',
    source: 'reader: HOEPA · the predatory loan',
  },
];

export default bank;
