import type { ExamItem } from '@/content/exam/types';

const bank: ExamItem[] = [
  {
    id: 'hpa-x01',
    unitId: 'hpa',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: "A borrower putting only 10% down is told she must buy private mortgage insurance. She asks who that insurance actually protects if she defaults. The correct answer is —",
    options: [
      'the borrower, by covering her missed payments',
      'the lender (and investor), not the borrower',
      'the appraiser who valued the home',
      'the servicer, by waiving its fees',
    ],
    correct: 1,
    explanation: "PMI pays the lender (and investor), not the borrower, if the borrower defaults — it does nothing for the borrower except make a low-down-payment loan possible. It does not cover the borrower's missed payments for her benefit.",
    difficulty: 'recall',
    source: 'reader: HPA · overview',
  },
  {
    id: 'hpa-x02',
    unitId: 'hpa',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: "A conforming loan is current, and its scheduled balance is about to reach 78% of the home's original value. What must the servicer do about PMI?",
    options: [
      'Nothing until the borrower requests cancellation',
      'Automatically terminate PMI, with no appraisal or good-payment showing needed',
      'Require a new appraisal before removing PMI',
      'Keep PMI until the loan reaches 80% LTV',
    ],
    correct: 1,
    explanation: "The servicer must automatically drop PMI once the loan is scheduled to reach 78% LTV of original value, provided the loan is current — no request, appraisal, or good-payment showing required. Eighty percent is the borrower-request threshold, not the automatic one.",
    difficulty: 'application',
    source: 'reader: HPA · automatic termination',
  },
  {
    id: 'hpa-x03',
    unitId: 'hpa',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: "A borrower reaches 80% LTV, has a clean payment record, and requests that PMI be cancelled — but the property carries a second mortgage. Can the servicer grant the request?",
    options: [
      'Yes — a good payment history alone qualifies him',
      'No — a subordinate lien on the property disqualifies a cancellation request',
      'Yes — second mortgages are irrelevant to PMI',
      'No — because request-based cancellation is not allowed at all',
    ],
    correct: 1,
    explanation: "Request-based cancellation at 80% LTV requires a good payment history AND no subordinate liens — a second mortgage disqualifies the request. Request-based cancellation does exist; the second lien is what blocks it here.",
    difficulty: 'application',
    source: 'reader: HPA · cancellation by request',
  },
  {
    id: 'hpa-x04',
    unitId: 'hpa',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: "A conventional loan is classified as high-risk (non-conforming) and stays current. At what LTV of original value does automatic PMI termination occur for this loan?",
    options: [
      '80%',
      '78%',
      '77%',
      'the amortization midpoint',
    ],
    correct: 2,
    explanation: "For a high-risk, non-conforming loan the automatic-termination point drops to 77% LTV, versus 78% for a conforming loan. The midpoint is the separate final-termination backstop, which does not even apply to high-risk loans.",
    difficulty: 'application',
    source: 'reader: HPA · automatic termination',
  },
  {
    id: 'hpa-x05',
    unitId: 'hpa',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: "A borrower fell behind for stretches and the loan never reached the 80% or 78% LTV triggers. Under HPA's final-termination backstop, when must PMI come off this (non-high-risk) loan?",
    options: [
      'When the loan reaches 80% LTV, no matter how long that takes',
      'At the midpoint of the loan\'s amortization period, regardless of payment status',
      'Never, because the borrower was delinquent',
      'Only after the borrower pays an appraisal fee',
    ],
    correct: 1,
    explanation: "Final termination requires PMI to come off at the midpoint of the amortization period regardless of payment status — the guarantee that PMI can't run the entire life of the loan. Because the loan never hit the LTV triggers, waiting for 80% would leave PMI on indefinitely.",
    difficulty: 'analysis',
    source: 'reader: HPA · final termination',
  },
  {
    id: 'hpa-x06',
    unitId: 'hpa',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: "After a borrower's PMI is cancelled, some premium the borrower paid has not yet been earned. Within how long must the servicer refund that unearned premium?",
    options: [
      '10 days',
      '30 days',
      '45 days',
      '60 days',
    ],
    correct: 2,
    explanation: "The servicer must refund any unearned premium within 45 days of cancellation or termination. The 30-day figure is the separate limit on how long after PMI ends a premium may still be charged, not the refund deadline.",
    difficulty: 'recall',
    source: 'reader: HPA · after PMI comes off',
  },
];

export default bank;
