// content/exam/bank/index.ts — GENERATED by scripts/gen-exam-index.mjs. Do not edit by hand.
import type { ExamItem } from '../types';
import b_arms from './arms';
import b_bsa_aml from './bsa-aml';
import b_construction_rehab from './construction-rehab';
import b_dnc_tsr from './dnc-tsr';
import b_dodd_frank from './dodd-frank';
import b_e_sign_act from './e-sign-act';
import b_ecoa from './ecoa';
import b_facta from './facta';
import b_fcra from './fcra';
import b_fha from './fha';
import b_ftc_red_flags_rule from './ftc-red-flags-rule';
import b_getting_licensed from './getting-licensed';
import b_glba from './glba';
import b_hmda from './hmda';
import b_hoepa from './hoepa';
import b_hpa from './hpa';
import b_keeping_the_license from './keeping-the-license';
import b_less_common_programs from './less-common-programs';
import b_maps_reg_n from './maps-reg-n';
import b_repayment_structures from './repayment-structures';
import b_respa from './respa';
import b_reverse_mortgages from './reverse-mortgages';
import b_second_liens from './second-liens';
import b_state_oversight from './state-oversight';
import b_temporary_authority_and_the_job from './temporary-authority-and-the-job';
import b_the_safe_act from './the-safe-act';
import b_tila from './tila';
import b_trid from './trid';
import b_usa_patriot_act from './usa-patriot-act';
import b_va_and_usda from './va-and-usda';
import b_what_a_mortgage_is from './what-a-mortgage-is';
import b_who_needs_a_license from './who-needs-a-license';

export const SECTION_BANK: Record<string, ExamItem[]> = {
  'arms': b_arms,
  'bsa-aml': b_bsa_aml,
  'construction-rehab': b_construction_rehab,
  'dnc-tsr': b_dnc_tsr,
  'dodd-frank': b_dodd_frank,
  'e-sign-act': b_e_sign_act,
  'ecoa': b_ecoa,
  'facta': b_facta,
  'fcra': b_fcra,
  'fha': b_fha,
  'ftc-red-flags-rule': b_ftc_red_flags_rule,
  'getting-licensed': b_getting_licensed,
  'glba': b_glba,
  'hmda': b_hmda,
  'hoepa': b_hoepa,
  'hpa': b_hpa,
  'keeping-the-license': b_keeping_the_license,
  'less-common-programs': b_less_common_programs,
  'maps-reg-n': b_maps_reg_n,
  'repayment-structures': b_repayment_structures,
  'respa': b_respa,
  'reverse-mortgages': b_reverse_mortgages,
  'second-liens': b_second_liens,
  'state-oversight': b_state_oversight,
  'temporary-authority-and-the-job': b_temporary_authority_and_the_job,
  'the-safe-act': b_the_safe_act,
  'tila': b_tila,
  'trid': b_trid,
  'usa-patriot-act': b_usa_patriot_act,
  'va-and-usda': b_va_and_usda,
  'what-a-mortgage-is': b_what_a_mortgage_is,
  'who-needs-a-license': b_who_needs_a_license,
};
