import type { ExamItem } from '@/content/exam/types';

const bank: ExamItem[] = [
  {
    id: 'keeping-the-license-x01',
    unitId: 'keeping-the-license',
    moduleId: 'uniform-state-content',
    area: 'ust',
    pool: 'section',
    stem: "An MLO forgot to renew, and it is now 12:01 a.m. on January 1. What must she do?",
    options: [
      'Keep originating until the state formally objects',
      'Pay a flat penalty and continue working',
      'Stop any activity that requires a license',
      'Wait exactly 30 days, then resume',
    ],
    correct: 2,
    explanation: 'Every license expires at 11:59 p.m. on December 31 and is dead at 12:00 a.m. on January 1. From that moment the MLO must stop any activity that requires a license.',
    difficulty: 'recall',
    source: 'reader: keeping the license · the December 31 deadline',
  },
  {
    id: 'keeping-the-license-x02',
    unitId: 'keeping-the-license',
    moduleId: 'uniform-state-content',
    area: 'ust',
    pool: 'section',
    stem: "An experienced MLO teaches 3 hours of an approved continuing-education course this year. How much CE credit does he earn for teaching it?",
    options: [
      '3 hours — an even trade',
      '6 hours — two hours of credit for every hour taught',
      '1.5 hours — half credit for instructors',
      'None — teaching does not count toward CE',
    ],
    correct: 1,
    explanation: 'If you teach an approved CE course, you earn two hours of credit for every one hour you teach. Three hours taught therefore yields six hours of credit.',
    difficulty: 'recall',
    source: 'reader: keeping the license · the fine print on CE',
  },
  {
    id: 'keeping-the-license-x03',
    unitId: 'keeping-the-license',
    moduleId: 'uniform-state-content',
    area: 'ust',
    pool: 'section',
    stem: "Knowing state agencies take time to process renewals, when is the smart moment for an MLO to submit hers?",
    options: [
      'Around November 1, well before the December 31 expiry',
      'On December 30, the day before it expires',
      'On January 2, just after the old one lapses',
      'Any time during the following calendar year',
    ],
    correct: 0,
    explanation: 'Because state agencies take time to process, the smart move is to submit the renewal early, around November 1, rather than gambling on the last week of December.',
    difficulty: 'application',
    source: 'reader: keeping the license · the December 31 deadline',
  },
  {
    id: 'keeping-the-license-x04',
    unitId: 'keeping-the-license',
    moduleId: 'uniform-state-content',
    area: 'ust',
    pool: 'section',
    stem: "An MLO wants to satisfy this year's CE hours by retaking the exact same approved course he completed last year. Is that allowed?",
    options: [
      'Yes — repeating a course is always fine',
      'Yes, but only if he also retakes the national exam',
      'No — the same approved course cannot be taken in the same or successive years',
      'Only if he has changed states since last year',
    ],
    correct: 2,
    explanation: "The CE rules block gaming: you cannot take the same approved course in the same or successive years. Repeating last year's course does not count.",
    difficulty: 'application',
    source: 'reader: keeping the license · the fine print on CE',
  },
  {
    id: 'keeping-the-license-x05',
    unitId: 'keeping-the-license',
    moduleId: 'uniform-state-content',
    area: 'ust',
    pool: 'section',
    stem: "An MLO let her state license lapse, but for the last 6 years she originated loans as a registered LO at a bank. She now wants a state license again. Must she retake the national exam?",
    options: [
      'Yes — 6 years exceeds the 5-year limit',
      "No — time spent as a registered LO doesn't count toward the 5-year lapse",
      'Yes — any lapse at all forces a re-exam',
      'No, but she must first wait another 30 days',
    ],
    correct: 1,
    explanation: 'A lapse of 5 years or more forces a re-exam, but time spent acting as a registered loan originator at an exempt entity does not count toward that lapse. Only time completely out of origination runs the clock.',
    difficulty: 'application',
    source: 'reader: keeping the license · the five-year lapse rule',
  },
  {
    id: 'keeping-the-license-x06',
    unitId: 'keeping-the-license',
    moduleId: 'uniform-state-content',
    area: 'ust',
    pool: 'section',
    stem: "A licensed MLO changes sponsorship to a new company. Who must report the change to the NMLS, and on what form?",
    options: [
      'Only the individual, on form MU1',
      'Only the company, on form MU4',
      'Both the individual and the company, on form MU4',
      'No one — the NMLS updates sponsorship automatically',
    ],
    correct: 2,
    explanation: 'When a licensed MLO changes sponsorship, the update is filed with the NMLS on form MU4, and both the individual and the company have to file it.',
    difficulty: 'analysis',
    source: 'reader: keeping the license · telling the NMLS',
  },
];

export default bank;
