import type { ExamItem } from '@/content/exam/types';

const bank: ExamItem[] = [
  {
    id: 'less-common-programs-x01',
    unitId: 'less-common-programs',
    moduleId: 'general-mortgage-knowledge',
    area: 'general',
    pool: 'section',
    stem: "On a graduated payment mortgage, the early payments start below the loan's true cost. What happens to the balance during those early years?",
    options: [
      'It stays flat, because payments cover the interest exactly',
      'It grows — the shortfall is added on, so the loan negatively amortizes at first',
      'It falls faster than a level-payment loan',
      'It is frozen until the payments step up',
    ],
    correct: 1,
    explanation: 'On a GPM the payments start below the true cost, so the shortfall is added to the balance — the loan negatively amortizes at first — then the payments step up on a set schedule.',
    difficulty: 'recall',
    source: 'reader: less-common programs · GPM',
  },
  {
    id: 'less-common-programs-x02',
    unitId: 'less-common-programs',
    moduleId: 'general-mortgage-knowledge',
    area: 'general',
    pool: 'section',
    stem: "A lender appraises a home for a package mortgage and includes the furniture and appliances inside it in the valuation. What does a package mortgage collateralize?",
    options: [
      'The land only',
      'The land, the dwelling, and the personal property inside it, as one appraised bundle',
      'The dwelling and a separate personal-property loan',
      'The land and dwelling, but never the contents',
    ],
    correct: 1,
    explanation: 'A package mortgage collateralizes the land, the dwelling, and the personal property inside it — furniture and appliances — appraised together as one bundle.',
    difficulty: 'recall',
    source: 'reader: less-common programs · package mortgage',
  },
  {
    id: 'less-common-programs-x03',
    unitId: 'less-common-programs',
    moduleId: 'general-mortgage-knowledge',
    area: 'general',
    pool: 'section',
    stem: "A borrower can afford more than the required payment and wants a fixed-rate loan that applies the extra to principal so the loan is paid off early. Which program fits?",
    options: [
      'A graduated payment mortgage (GPM)',
      'A growth equity mortgage (GEM)',
      'A reduction option mortgage (ROM)',
      'A land contract',
    ],
    correct: 1,
    explanation: "A growth equity mortgage is a fixed-rate loan whose payments start higher than required and rise, with the extra applied to principal, so the loan is paid off early. A GPM does the opposite — it starts low.",
    difficulty: 'application',
    source: 'reader: less-common programs · GEM',
  },
  {
    id: 'less-common-programs-x04',
    unitId: 'less-common-programs',
    moduleId: 'general-mortgage-knowledge',
    area: 'general',
    pool: 'section',
    stem: "Under a land contract, a buyer has moved in and is paying the seller directly, but stops paying two years in. What is the buyer's position on title and on the payments already made?",
    options: [
      'They already hold the deed and keep their equity',
      'They have possession but not the deed, and can forfeit the payments made',
      'They hold title but must return possession',
      'They receive a refund of all payments made',
    ],
    correct: 1,
    explanation: 'Under a land contract the buyer takes possession but not the deed — they pay the seller directly and receive title only when the balance is paid. Walk away early and the payments made can be forfeit.',
    difficulty: 'application',
    source: 'reader: less-common programs · land contract',
  },
  {
    id: 'less-common-programs-x05',
    unitId: 'less-common-programs',
    moduleId: 'general-mortgage-knowledge',
    area: 'general',
    pool: 'section',
    stem: "A borrower wants the ability to drop their fixed rate once if market rates fall, without going through a full refinance. Which program offers that?",
    options: [
      'A graduated payment mortgage',
      'A reduction option mortgage (ROM)',
      'A package mortgage',
      'A growth equity mortgage',
    ],
    correct: 1,
    explanation: 'A reduction option mortgage is a fixed-rate loan with a one-time option to lower the rate without a full refinance, usually for a fee and within a set window.',
    difficulty: 'application',
    source: 'reader: less-common programs · ROM',
  },
  {
    id: 'less-common-programs-x06',
    unitId: 'less-common-programs',
    moduleId: 'general-mortgage-knowledge',
    area: 'general',
    pool: 'section',
    stem: "A GPM and a GEM are both fixed-rate, but their payment schedules move in opposite directions. How does the balance behave in each early on?",
    options: [
      "Both balances fall faster than a level-payment loan",
      "The GPM's balance grows at first (negative amortization); the GEM's balance falls faster as extra goes to principal",
      "The GPM's balance falls faster; the GEM's grows at first",
      "Both balances stay flat until the payments change",
    ],
    correct: 1,
    explanation: 'A GPM starts with low payments that don\'t cover the interest, so the balance grows (negative amortization) before the payments step up. A GEM starts with payments higher than required, with the extra going to principal, so the balance falls faster and the loan is paid off early.',
    difficulty: 'analysis',
    source: 'reader: less-common programs · GPM vs GEM',
  },
];

export default bank;
