import type { ExamItem } from '@/content/exam/types';

const bank: ExamItem[] = [
  {
    id: 'maps-reg-n-x01',
    unitId: 'maps-reg-n',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: "A compliance officer is reviewing a mortgage flyer and cites the rule that keeps mortgage advertising honest. Under which regulation is that rule (MAPs) implemented?",
    options: [
      'Regulation N',
      'Regulation X',
      'Regulation Z',
      'Regulation B',
    ],
    correct: 0,
    explanation: "Mortgage Acts and Practices–Advertising (MAPs) was issued under Regulation N in 2009. Regulation X is RESPA and Regulation Z is TILA — MAPs is a close cousin of TILA's advertising rules but sits under Reg N.",
    difficulty: 'recall',
    source: 'reader: MAPs (Reg N) · what MAPs is',
  },
  {
    id: 'maps-reg-n-x02',
    unitId: 'maps-reg-n',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: "A mortgage mailer headlines 'No fees!' even though the loan carries an origination fee. Does this violate MAPs?",
    options: [
      "No — as long as the fee is disclosed at closing",
      'Yes — misrepresenting the existence or amount of fees is prohibited',
      'No — advertising fees is optional under MAPs',
      'Yes — but only if the rate is also misstated',
    ],
    correct: 1,
    explanation: "MAPs bars any material misrepresentation about a mortgage, expressly including claiming there are no fees when fees exist. A later closing disclosure does not cure a misleading ad, and no additional misstatement is needed for the violation.",
    difficulty: 'application',
    source: 'reader: MAPs (Reg N) · the one rule underneath',
  },
  {
    id: 'maps-reg-n-x03',
    unitId: 'maps-reg-n',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: "An ad promotes a loan as offering a 'fixed' rate, but the product's rate can actually adjust after an intro period. Under MAPs, this is —",
    options: [
      'permitted, because the intro rate really is fixed for a while',
      'a prohibited material misrepresentation about whether the rate is fixed',
      'allowed if the word appears in small print',
      'outside the scope of MAPs',
    ],
    correct: 1,
    explanation: "Whether a rate is truly 'fixed' is one of the specific things MAPs says an ad may not misrepresent. Calling an adjustable product 'fixed' misleads the borrower about the loan, which is exactly what the rule reaches — small print does not save it.",
    difficulty: 'application',
    source: 'reader: MAPs (Reg N) · the one rule underneath',
  },
  {
    id: 'maps-reg-n-x04',
    unitId: 'maps-reg-n',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: "A mortgage ad states a specific monthly payment amount of '$900/month.' Under the triggering-term rule MAPs carries over from TILA, what must the ad then clearly disclose?",
    options: [
      "Only the lender's phone number",
      'The down payment, the actual repayment terms over the whole loan, and the APR',
      "Just the loan originator's name",
      'Nothing further, since a payment is not a triggering term',
    ],
    correct: 1,
    explanation: "A stated payment amount is a triggering term, so the ad must then disclose the down payment, the actual repayment terms over the whole loan (including any balloon), and the annual percentage rate using that term. A tempting figure can't travel alone.",
    difficulty: 'application',
    source: 'reader: MAPs (Reg N) · triggering terms, again',
  },
  {
    id: 'maps-reg-n-x05',
    unitId: 'maps-reg-n',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: "A lender sends a mailer deliberately designed to look as though it comes from the recipient's current lender, when it is actually from a competitor. Does MAPs reach this?",
    options: [
      'No — MAPs only governs the interest rate and fees quoted',
      "Yes — misrepresenting whether the ad comes from the consumer's current lender is prohibited",
      'No — the source of a mailer is not a mortgage term',
      'Yes — but only if the rate quoted is also false',
    ],
    correct: 1,
    explanation: "MAPs' single principle bars any material misrepresentation about a mortgage credit product, and the unit lists 'whether the ad comes from your current lender' among them. Disguising the source misleads the borrower, so the rule reaches it even if the quoted rate is accurate.",
    difficulty: 'analysis',
    source: 'reader: MAPs (Reg N) · the one rule underneath',
  },
  {
    id: 'maps-reg-n-x06',
    unitId: 'maps-reg-n',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: "So that a violation can later be traced, a company that runs mortgage ads must keep copies of its materially different ads and the materials behind them. For how long?",
    options: [
      'At least 6 months',
      'At least 12 months',
      'At least 24 months',
      'At least 5 years',
    ],
    correct: 2,
    explanation: "MAPs requires the advertiser to retain copies of all materially different commercial communications — plus sales scripts, training, and marketing materials, and records of the products available while the ad ran — for at least 24 months. The shorter windows fall short.",
    difficulty: 'recall',
    source: 'reader: MAPs (Reg N) · keeping the ads on file',
  },
];

export default bank;
