import type { ExamItem } from '@/content/exam/types';

const bank: ExamItem[] = [
  {
    id: 'repayment-structures-x01',
    unitId: 'repayment-structures',
    moduleId: 'general-mortgage-knowledge',
    area: 'general',
    pool: 'section',
    stem: "During the interest-only period of a loan, a borrower makes every payment on time yet the balance never drops. Why?",
    options: [
      'The payments cover only the interest, so nothing goes to principal',
      'The lender is applying payments to escrow first',
      'The rate is adjusting upward each month',
      'The loan is negatively amortizing',
    ],
    correct: 0,
    explanation: 'On an interest-only loan the borrower pays only the interest for a set period, so the balance holds flat — nothing is going to principal. The payment covers the interest exactly, so the balance neither grows nor shrinks.',
    difficulty: 'recall',
    source: 'reader: how a loan gets repaid · interest-only',
  },
  {
    id: 'repayment-structures-x02',
    unitId: 'repayment-structures',
    moduleId: 'general-mortgage-knowledge',
    area: 'general',
    pool: 'section',
    stem: "A borrower with a balloon loan wants to keep the conditional right to modify (CRTM) instead of paying the balloon at the call date. By when must they give written notice?",
    options: [
      'No later than 45 days before the call date',
      'No later than 90 days before the call date',
      'On the call date itself',
      'Within 45 days after the call date',
    ],
    correct: 0,
    explanation: 'To exercise a CRTM — converting the balloon to a fixed rate instead of paying it — the borrower must give written notice no later than 45 days before the call.',
    difficulty: 'recall',
    source: 'reader: how a loan gets repaid · the call (CRTM)',
  },
  {
    id: 'repayment-structures-x03',
    unitId: 'repayment-structures',
    moduleId: 'general-mortgage-knowledge',
    area: 'general',
    pool: 'section',
    stem: "A note describes the loan as a 3/27 balloon. What do those two numbers tell the borrower?",
    options: [
      'The rate is fixed 3 years, then adjusts for 27',
      'The payment is set on a 30-year amortization, but the full balance is called at year 3',
      'The balloon is due at year 27 with a 3-year interest-only start',
      'The loan is paid off entirely in 3 years',
    ],
    correct: 1,
    explanation: "A balloon is written as two numbers — years to the call, then the amortization behind the payment. A 3/27 is paid like a 30-year loan (3 + 27) but the entire remaining balance comes due at year three.",
    difficulty: 'application',
    source: 'reader: how a loan gets repaid · the call (balloon)',
  },
  {
    id: 'repayment-structures-x04',
    unitId: 'repayment-structures',
    moduleId: 'general-mortgage-knowledge',
    area: 'general',
    pool: 'section',
    stem: "A borrower asks their bank for a plain interest-only feature on a standard conforming loan and is told it isn't available that way. Where does the reader say interest-only actually lives?",
    options: [
      'On any conventional fixed-rate loan',
      'Only as a feature of a non-QM mortgage kept in portfolio or sold to a private investor',
      'Only on FHA-insured loans',
      'Only on VA and USDA loans',
    ],
    correct: 1,
    explanation: 'Interest-only exists only as a feature of a non-QM mortgage: a lender either keeps it in portfolio or sells it to a private investor. It is not a standard conforming-loan feature.',
    difficulty: 'application',
    source: 'reader: how a loan gets repaid · interest-only',
  },
  {
    id: 'repayment-structures-x05',
    unitId: 'repayment-structures',
    moduleId: 'general-mortgage-knowledge',
    area: 'general',
    pool: 'section',
    stem: "A borrower makes a large lump-sum principal payment and asks the servicer to re-cast the loan rather than let it run as usual. Compared with the normal result of a lump-sum payment, what does a re-cast do?",
    options: [
      'It lowers the interest rate against the smaller balance',
      'It recomputes a lower monthly payment over the remaining term, instead of keeping the payment and shortening the term',
      'It extends the term to reduce the payment',
      'It converts the loan to interest-only',
    ],
    correct: 1,
    explanation: 'Normally a lump-sum principal payment keeps the payment the same and shortens the term. A re-cast does the opposite: the servicer recomputes a lower payment against the new, smaller balance over the remaining term. It is discretionary, often carries a fee, and the interest rate never changes.',
    difficulty: 'application',
    source: 'reader: how a loan gets repaid · re-cast',
  },
  {
    id: 'repayment-structures-x06',
    unitId: 'repayment-structures',
    moduleId: 'general-mortgage-knowledge',
    area: 'general',
    pool: 'section',
    stem: "A borrower pays interest-only for the first 15 years of a 30-year loan; then it re-casts. The new payment is higher than if the loan had amortized from day one. Why?",
    options: [
      'The interest rate rises at the re-cast',
      'The full original balance must now amortize over just the 15 remaining years',
      'A prepayment penalty is added to the payment',
      'The lender adds back the skipped principal as a lump sum',
    ],
    correct: 1,
    explanation: 'Because nothing went to principal during the interest-only years, the balance never fell. At the re-cast, the full original principal has to amortize over the shorter remaining term (15 years instead of 30), so each payment must be larger.',
    difficulty: 'analysis',
    source: 'reader: how a loan gets repaid · interest-only re-cast',
  },
];

export default bank;
