import type { ExamItem } from '@/content/exam/types';

const bank: ExamItem[] = [
  {
    id: 'respa-x01',
    unitId: 'respa',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: 'A title company pays a real estate agent $150 for every buyer the agent steers to it who then closes. The company is convicted of violating RESPA’s anti-kickback rule. What is the maximum criminal penalty it faces?',
    options: [
      'Treble damages — three times the charges made',
      'A fine of up to $10,000, imprisonment for up to one year, or both',
      'A fine of up to $27,592 per violation',
      'Imprisonment for up to five years and permanent loss of license',
    ],
    correct: 1,
    explanation: 'Section 8 violations carry a fine of up to $10,000, up to one year’s imprisonment, or both. Treble damages is the Section 9 remedy — it applies when a seller forces a buyer to use a particular title company, not to kickbacks. The $27,592 figure is HOEPA’s points-and-fees threshold, unrelated here.',
    difficulty: 'recall',
    source: 'reader: RESPA · Section 8 penalties',
  },
  {
    id: 'respa-x02',
    unitId: 'respa',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: 'A borrower applies to refinance the mortgage on the home she already lives in. The lender is deciding which opening disclosures it owes. Must it give her the Special Information Booklet (the HUD Home Loan Toolkit)?',
    options: [
      'Yes — every mortgage applicant must receive it within 3 general business days',
      'Yes, but only because the loan is secured by a primary residence',
      'No — refinances are exempt from the Special Information Booklet requirement',
      'No — but only if a mortgage broker takes the application',
    ],
    correct: 2,
    explanation: 'The Special Information Booklet is not required for a refinance, a closed-end subordinate lien, a reverse mortgage, or any loan not for purchasing a 1–4 unit dwelling. It is required within 3 general business days on a purchase, but this is a refinance. The broker-issues rule shifts who delivers it — it does not create the obligation here.',
    difficulty: 'recall',
    source: 'reader: RESPA · special information booklet',
  },
  {
    id: 'respa-x03',
    unitId: 'respa',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: 'A loan officer refers a borrower to a title company in which the loan officer’s spouse holds a 5% ownership interest. A mortgage application is involved. What must the loan officer do?',
    options: [
      'Nothing — the spouse’s stake is below the 1% ownership trigger',
      'Issue an Affiliated Business Arrangement Disclosure at the time of referral or within three business days',
      'Nothing — title services are an exempt category that never requires disclosure',
      'Refer the borrower to a different title company, because the arrangement is illegal',
    ],
    correct: 1,
    explanation: 'An affiliated business arrangement exists at more than 1% direct ownership, and a spouse is an associate — so the 5% stake triggers an ABAD, due at referral or within three business days when an application is involved. The 1% threshold is exceeded, not missed. Title is not an exempt category (the exemptions are appraiser, credit repository, lender attorney, mortgage insurance, flood search, tax search). The arrangement is legal so long as the disclosure is made.',
    difficulty: 'application',
    source: 'reader: RESPA · affiliated business arrangement disclosure',
  },
  {
    id: 'respa-x04',
    unitId: 'respa',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: 'An escrow analysis reveals a $1,000 shortage on an account whose monthly escrow payment is $400. Because the shortage exceeds one monthly payment, what are the servicer’s options?',
    options: [
      'Do nothing, or spread repayment over at least 12 months interest-free',
      'Demand the full $1,000 as a lump sum within 30 days',
      'Refund the difference to the borrower within 30 days',
      'Require repayment in two equal monthly installments',
    ],
    correct: 0,
    explanation: 'When a shortage equals or exceeds one monthly escrow payment, only two options remain: do nothing, or spread repayment over at least 12 months interest-free. The 30-day lump-sum demand is available only when the shortage is less than one monthly payment. Refunding is the rule for a surplus of $50 or more, not a shortage. Two monthly installments is a deficiency option, not a shortage option.',
    difficulty: 'application',
    source: 'reader: RESPA · escrow shortage, surplus, and deficiency',
  },
  {
    id: 'respa-x05',
    unitId: 'respa',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: 'Twenty days after a servicing transfer, a borrower accidentally mails his payment to the old servicer, so the new servicer receives nothing on time. What may the new servicer do?',
    options: [
      'Charge a late fee, since the payment did not reach the correct servicer',
      'Report the late payment to the credit bureaus immediately',
      'Neither charge a late fee nor report the payment as late during this period',
      'Accelerate the loan for non-payment',
    ],
    correct: 2,
    explanation: 'During the 60-calendar-day period beginning on the transfer date, the new servicer cannot charge late fees or report late payments to credit bureaus when the borrower mistakenly pays the old servicer. Twenty days is inside that window, so late fees and adverse reporting are both off the table until the 60 days pass.',
    difficulty: 'application',
    source: 'reader: RESPA · transfer of servicing disclosure',
  },
  {
    id: 'respa-x06',
    unitId: 'respa',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: 'A borrower defaults in a state where loans are secured by a Deed of Trust rather than a Mortgage. What type of foreclosure applies, and why does the security instrument decide it?',
    options: [
      'Judicial foreclosure, because a court order is always required to sell a home',
      'Non-judicial foreclosure, because the security instrument determines the foreclosure type',
      'Judicial foreclosure, because a Deed of Trust gives the borrower a redemption period',
      'Either type, at the lender’s discretion',
    ],
    correct: 1,
    explanation: 'The type of security instrument determines the type of foreclosure: a Mortgage leads to judicial foreclosure and a Deed of Trust leads to non-judicial foreclosure. Judicial foreclosure with its court order and state-defined redemption period is the Mortgage path, not the Deed of Trust path. The choice is set by state law and the instrument, not left to the lender.',
    difficulty: 'analysis',
    source: 'reader: RESPA · judicial vs non-judicial foreclosure',
  },
];

export default bank;
