import type { ExamItem } from '@/content/exam/types';

const bank: ExamItem[] = [
  {
    id: 'reverse-mortgages-x01',
    unitId: 'reverse-mortgages',
    moduleId: 'general-mortgage-knowledge',
    area: 'general',
    pool: 'section',
    stem: "A 64-year-old homeowner wants to pull cash from her home's equity, stay living there, and make no monthly mortgage payment. Which requirement must she meet for a reverse mortgage, and what happens to the interest?",
    options: [
      'She must be at least 55; interest is paid monthly',
      'She must be at least 62; interest accrues onto the balance instead of being paid down',
      'She must be at least 70; interest is forgiven',
      'She must be at least 62; interest is escrowed and refunded',
    ],
    correct: 1,
    explanation: 'A reverse mortgage lets an owner 62 or older draw equity as cash while staying in the home with no monthly payment required. Interest accrues onto the balance rather than being paid down; the loan comes due only when the last borrower leaves.',
    difficulty: 'recall',
    source: 'reader: reverse mortgages · age 62+ and no monthly payment',
  },
  {
    id: 'reverse-mortgages-x02',
    unitId: 'reverse-mortgages',
    moduleId: 'general-mortgage-knowledge',
    area: 'general',
    pool: 'section',
    stem: "A married couple, ages 68 and 74, apply for a reverse mortgage together. Whose age drives the principal limit — the maximum the loan will lend?",
    options: [
      'The older borrower\'s age',
      'The younger borrower\'s age',
      'The average of both ages',
      'It does not depend on age',
    ],
    correct: 1,
    explanation: "The youngest borrower's age sets the principal limit. Older borrowers can draw more because the balance has less time to grow against the home's value; using the younger age is the conservative measure.",
    difficulty: 'recall',
    source: 'reader: reverse mortgages · how much, and how it comes out',
  },
  {
    id: 'reverse-mortgages-x03',
    unitId: 'reverse-mortgages',
    moduleId: 'general-mortgage-knowledge',
    area: 'general',
    pool: 'section',
    stem: "A new reverse-mortgage borrower with no existing mortgage to pay off wants to take as much cash as possible right away. In the first year, how much of the principal limit can she access?",
    options: [
      'The full principal limit',
      'No more than 60% of the principal limit',
      'No more than 40% of the principal limit',
      'Only the tenure payment amount',
    ],
    correct: 1,
    explanation: 'A first-year cap lets the borrower access no more than 60% of the principal limit up front (with room for a bit more only if it is needed to pay off an existing mortgage). With no existing mortgage, 60% is the ceiling.',
    difficulty: 'application',
    source: 'reader: reverse mortgages · the 60% first-year rule',
  },
  {
    id: 'reverse-mortgages-x04',
    unitId: 'reverse-mortgages',
    moduleId: 'general-mortgage-knowledge',
    area: 'general',
    pool: 'section',
    stem: "A reverse-mortgage borrower moves into an assisted-living facility and has not returned to the home for 14 straight months. What is the consequence for the loan?",
    options: [
      'Nothing changes as long as taxes are paid',
      'It becomes a triggering event, and the loan comes due',
      'The loan converts to a forward mortgage',
      'The lender must offer a new draw period',
    ],
    correct: 1,
    explanation: 'Being out of the home for more than 12 straight months is a triggering event that makes a reverse mortgage due. Other triggers are the last borrower dying with no surviving spouse, the home being sold, or taxes and insurance lapsing.',
    difficulty: 'application',
    source: 'reader: reverse mortgages · triggering events',
  },
  {
    id: 'reverse-mortgages-x05',
    unitId: 'reverse-mortgages',
    moduleId: 'general-mortgage-knowledge',
    area: 'general',
    pool: 'section',
    stem: "A borrower wants a monthly reverse-mortgage payment that keeps coming for as long as she lives in the home, rather than a larger amount that stops after a set number of years. Which annuity option does she want?",
    options: [
      'Term',
      'Tenure',
      'Lump sum',
      'Line of credit',
    ],
    correct: 1,
    explanation: 'Tenure pays a set amount for as long as the borrower lives in the home; term pays a larger amount for a fixed number of years. She wants the tenure option.',
    difficulty: 'application',
    source: 'reader: reverse mortgages · tenure vs term',
  },
  {
    id: 'reverse-mortgages-x06',
    unitId: 'reverse-mortgages',
    moduleId: 'general-mortgage-knowledge',
    area: 'general',
    pool: 'section',
    stem: "A HECM balance has grown past the home's value. The borrower dies and the heirs want to keep or sell the property. Because the loan is non-recourse, what do the heirs owe beyond the home itself?",
    options: [
      'The full shortfall from the estate',
      'Nothing — the FHA insurance covers the gap',
      'Half of the shortfall',
      'The accrued interest only',
    ],
    correct: 1,
    explanation: 'A HECM is non-recourse, so the debt is limited to the home\'s value. If the balance exceeds that value, the FHA mortgage insurance covers the shortfall — never the borrower or the heirs, who can settle by handing over the property and owe nothing more.',
    difficulty: 'analysis',
    source: 'reader: reverse mortgages · non-recourse',
  },
];

export default bank;
