import type { ExamItem } from '@/content/exam/types';

const bank: ExamItem[] = [
  {
    id: 'second-liens-x01',
    unitId: 'second-liens',
    moduleId: 'general-mortgage-knowledge',
    area: 'general',
    pool: 'section',
    stem: "A homeowner wants to tap equity but isn't sure how much they'll need or when — they want to borrow, pay down, and borrow again over time. Which second-lien product fits?",
    options: [
      'A home-equity loan, because it pays a fixed lump sum',
      'A HELOC, because it is an open-end revolving line',
      'A purchase-money second mortgage',
      'A construction loan',
    ],
    correct: 1,
    explanation: 'A HELOC is an open-end line the borrower draws, repays, and draws again like a credit card — the fit for an open-ended need. A home-equity loan pays one fixed lump sum on a set schedule (closed-end), better for a known one-time cost.',
    difficulty: 'recall',
    source: 'reader: second liens · the line you draw against',
  },
  {
    id: 'second-liens-x02',
    unitId: 'second-liens',
    moduleId: 'general-mortgage-knowledge',
    area: 'general',
    pool: 'section',
    stem: "A borrower asks why the rate on a second lien is a little higher than on their first mortgage. What is the reason the reader gives?",
    options: [
      'Second liens are always variable-rate',
      'If the home is sold to clear its debts, the first mortgage is paid first and the second waits for whatever is left — a riskier position',
      'Second liens require mortgage insurance',
      'The second lien has a shorter term',
    ],
    correct: 1,
    explanation: 'A second lien stands behind the first: if the house were sold to clear its debts, the first mortgage is paid off first and the second waits for whatever\'s left. Standing at the back of that line is riskier for the lender, so a second lien usually costs a little more.',
    difficulty: 'recall',
    source: 'reader: second liens · standing at the back of the line',
  },
  {
    id: 'second-liens-x03',
    unitId: 'second-liens',
    moduleId: 'general-mortgage-knowledge',
    area: 'general',
    pool: 'section',
    stem: "A HELOC borrower reaches the end of the roughly ten-year window during which they could draw. What happens to the line next?",
    options: [
      'The line renews for another ten years automatically',
      'The line freezes and the remaining balance amortizes over the years left',
      'The full balance becomes due immediately as a balloon',
      'The rate converts to fixed and draws continue',
    ],
    correct: 1,
    explanation: 'The draw period runs about ten years; when it closes, the line freezes and the remaining balance amortizes over the years left. During the draw period the borrower is usually billed interest-only on the outstanding balance.',
    difficulty: 'application',
    source: 'reader: second liens · the line you draw against',
  },
  {
    id: 'second-liens-x04',
    unitId: 'second-liens',
    moduleId: 'general-mortgage-knowledge',
    area: 'general',
    pool: 'section',
    stem: "Two borrowers each take a second lien. One's rate is fixed for the life of the loan; the other's moves with the Prime rate. Which product has the rate that tracks Prime?",
    options: [
      'The home-equity loan',
      'The HELOC',
      'The purchase-money second',
      'Both track Prime',
    ],
    correct: 1,
    explanation: 'A HELOC usually carries a variable rate tied to the Prime rate, while a home-equity loan is a fixed-rate lump sum. The one that tracks Prime is the HELOC.',
    difficulty: 'application',
    source: 'reader: second liens · the line you draw against',
  },
  {
    id: 'second-liens-x05',
    unitId: 'second-liens',
    moduleId: 'general-mortgage-knowledge',
    area: 'general',
    pool: 'section',
    stem: "A buyer short on the down payment sets up a second lien on the very day they close, using it to cover part of the price so they can skip mortgage insurance. What is this second lien called?",
    options: [
      'A HELOC drawn after closing',
      'A purchase-money second mortgage',
      'A reverse mortgage',
      'A home-equity loan against built-up equity',
    ],
    correct: 1,
    explanation: 'A purchase-money second mortgage is taken out at the time of purchase — not later against built-up equity — typically to cover part of the price and avoid PMI. A HELOC or home-equity loan is drawn later against equity already built up.',
    difficulty: 'application',
    source: 'reader: second liens · skipping mortgage insurance',
  },
  {
    id: 'second-liens-x06',
    unitId: 'second-liens',
    moduleId: 'general-mortgage-knowledge',
    area: 'general',
    pool: 'section',
    stem: "A buyer puts only 10% down using an 80/10/10 structure and pays no PMI, even though a single loan with 10% down would trigger it. Why does the piggyback avoid PMI?",
    options: [
      'The two liens combined stay under 90% CLTV',
      'PMI keys off the first lien\'s LTV, and the first mortgage is only 80% of value',
      'Second liens are exempt from PMI by law',
      'The 10% second lien counts as the down payment',
    ],
    correct: 1,
    explanation: 'PMI kicks in only when the first mortgage is above 80% of the home\'s value — it keys off the first lien\'s LTV, not the buyer\'s down payment. In an 80/10/10 the first mortgage is only 80% of value, so no PMI attaches; the 10% second lien covers the rest.',
    difficulty: 'analysis',
    source: 'reader: second liens · skipping mortgage insurance',
  },
];

export default bank;
