import type { ExamItem } from '@/content/exam/types';

const bank: ExamItem[] = [
  {
    id: 'state-oversight-x01',
    unitId: 'state-oversight',
    moduleId: 'uniform-state-content',
    area: 'ust',
    pool: 'section',
    stem: "A State Commissioner determines that an MLO defrauded borrowers. Which response is within her authority under the state SAFE Act?",
    options: [
      'Revoke the license and order restitution and penalties',
      'Imprison the originator without a hearing',
      "Seize the borrower's home to satisfy claims",
      'Waive federal law for the affected loans',
    ],
    correct: 0,
    explanation: 'A State Commissioner has broad authority: to deny, suspend, condition, or revoke licenses, and to order restitution and penalties, issue cease-and-desist orders, subpoena, and ban an individual from the industry.',
    difficulty: 'recall',
    source: 'reader: state oversight · the state model law and the commissioner',
  },
  {
    id: 'state-oversight-x02',
    unitId: 'state-oversight',
    moduleId: 'uniform-state-content',
    area: 'ust',
    pool: 'section',
    stem: "An MLO commits three separate violations of the Act. How does the civil-penalty ceiling apply?",
    options: [
      '$25,000 total, split across all three',
      'Up to $25,000 for each act or omission, so the penalties stack',
      '$25,000, charged only for the first violation',
      'There is no monetary ceiling at all',
    ],
    correct: 1,
    explanation: 'The ceiling on a civil penalty is $25,000 for each act or omission, and each separate violation counts on its own, so they stack.',
    difficulty: 'recall',
    source: 'reader: state oversight · penalties and call reports',
  },
  {
    id: 'state-oversight-x03',
    unitId: 'state-oversight',
    moduleId: 'uniform-state-content',
    area: 'ust',
    pool: 'section',
    stem: "A mortgage licensee entity must keep regulators informed about its origination activity. How often is the Call Report filed with the NMLS, and what does it cover?",
    options: [
      'Annually, covering the full prior year',
      'Monthly, covering the prior month',
      'Quarterly, describing the origination activity of the previous calendar quarter',
      'Only when the Commissioner opens an audit',
    ],
    correct: 2,
    explanation: 'Every mortgage licensee entity files a Call Report — a report of condition submitted to the NMLS quarterly, describing the origination activity of the previous calendar quarter.',
    difficulty: 'application',
    source: 'reader: state oversight · penalties and call reports',
  },
  {
    id: 'state-oversight-x04',
    unitId: 'state-oversight',
    moduleId: 'uniform-state-content',
    area: 'ust',
    pool: 'section',
    stem: "During an examination, an MLO shreds files he fears will make him look bad. How does the SAFE Act treat that?",
    options: [
      'Permitted, because the files belong to him',
      'It is itself a serious violation — records may not be knowingly withheld, altered, or destroyed',
      'Fine, as long as he does it after the exam concludes',
      'Allowed if the borrower consents to the destruction',
    ],
    correct: 1,
    explanation: 'No one under examination may knowingly withhold, alter, or destroy records. Doing so is itself a serious violation.',
    difficulty: 'application',
    source: 'reader: state oversight · investigation and examination',
  },
  {
    id: 'state-oversight-x05',
    unitId: 'state-oversight',
    moduleId: 'uniform-state-content',
    area: 'ust',
    pool: 'section',
    stem: "A broker advertises an eye-catching low rate that is not actually available, purely to get callers on the phone. Under the SAFE Act, what is this?",
    options: [
      'Permitted lead-generation marketing',
      'Allowed as long as the real rate is disclosed later',
      'A prohibited practice — advertising rates that are not actually available is bait-and-switch',
      'A state courtesy issue, not a prohibited act',
    ],
    correct: 2,
    explanation: 'It is a violation to advertise or contract for rates and terms that are not actually available — the classic bait-and-switch the SAFE Act prohibits.',
    difficulty: 'application',
    source: 'reader: state oversight · the prohibitions',
  },
  {
    id: 'state-oversight-x06',
    unitId: 'state-oversight',
    moduleId: 'uniform-state-content',
    area: 'ust',
    pool: 'section',
    stem: "Two MLOs at the same firm produce very different loan volumes. How are their surety-bond and net-worth requirements determined, and can the employer help?",
    options: [
      'Both are fixed by federal statute at a flat figure for all MLOs',
      'They scale with the dollar amount of loans originated, and an employer’s bond can cover its employees',
      'Both are set at $25,000 each, regardless of volume',
      'They are set by the FBI as part of the background check',
    ],
    correct: 1,
    explanation: 'The bond amount and net worth are not fixed dollar figures; they scale with the dollar amount of loans the originator produces, as the State Commissioner sets. An employer’s bond can cover its employees.',
    difficulty: 'analysis',
    source: 'reader: state oversight · surety bonds and net worth',
  },
];

export default bank;
