import type { ExamItem } from '@/content/exam/types';

const bank: ExamItem[] = [
  {
    id: 'temporary-authority-and-the-job-x01',
    unitId: 'temporary-authority-and-the-job',
    moduleId: 'uniform-state-content',
    area: 'ust',
    pool: 'section',
    stem: "A registered LO at a bank takes a job at a state-licensed mortgage company and wants temporary authority to work while his application is pending. During what window must he have been registered in the NMLS?",
    options: [
      'At some point during the 1-year period before applying',
      'At some point during the 30-day period before applying',
      'At some point during the 120-day period before applying',
      'At some point during the 5-year period before applying',
    ],
    correct: 0,
    explanation: 'A registered LO joining a state-licensed company gets temporary authority if his record is clean, he has submitted a state license application, and he was registered in the NMLS at some point during the 1-year period before applying.',
    difficulty: 'recall',
    source: 'reader: temporary authority & on the job · the registered path',
  },
  {
    id: 'temporary-authority-and-the-job-x02',
    unitId: 'temporary-authority-and-the-job',
    moduleId: 'uniform-state-content',
    area: 'ust',
    pool: 'section',
    stem: "An MLO completes a Closing Disclosure and reaches a line that simply does not apply to this loan. How should she handle it?",
    options: [
      "Type 'N/A' in the field",
      "Leave it blank — 'N/A' is prohibited",
      'Cross the line out with a pen',
      'Fill the field with zeros',
    ],
    correct: 1,
    explanation: "On the Loan Estimate and Closing Disclosure, the entry 'N/A' is prohibited. A line that does not apply is simply left blank.",
    difficulty: 'recall',
    source: "reader: temporary authority & on the job · the identifier, the file, and 'N/A'",
  },
  {
    id: 'temporary-authority-and-the-job-x03',
    unitId: 'temporary-authority-and-the-job',
    moduleId: 'uniform-state-content',
    area: 'ust',
    pool: 'section',
    stem: "A state-licensed MLO in Nevada takes a job at a licensed company in Arizona and applies for an Arizona license. She qualifies for temporary authority if she held a license in a different state during what window?",
    options: [
      'The 1-year period before applying',
      'The 120-day period before applying',
      'The 30-day period before submitting the new application',
      'The 5-year period before applying',
    ],
    correct: 2,
    explanation: 'A state-licensed originator gets temporary authority in the new state if she meets standard requirements, is employed by a licensed company there, and held a license in a different state at some point during the 30-day period before submitting the new application.',
    difficulty: 'application',
    source: 'reader: temporary authority & on the job · the licensed path',
  },
  {
    id: 'temporary-authority-and-the-job-x04',
    unitId: 'temporary-authority-and-the-job',
    moduleId: 'uniform-state-content',
    area: 'ust',
    pool: 'section',
    stem: "An MLO working under temporary authority has an application that is still sitting incomplete after 120 days. What happens to her authority?",
    options: [
      'It continues indefinitely until the license issues',
      'It ends — 120 days with the application still incomplete is one of the ending events',
      'It resets for another 120 days automatically',
      'Nothing — incompleteness has no effect on the window',
    ],
    correct: 1,
    explanation: 'Temporary authority ends at the earliest of four events, one of which is 120 days passing with the application still sitting incomplete.',
    difficulty: 'application',
    source: 'reader: temporary authority & on the job · when temporary authority ends',
  },
  {
    id: 'temporary-authority-and-the-job-x05',
    unitId: 'temporary-authority-and-the-job',
    moduleId: 'uniform-state-content',
    area: 'ust',
    pool: 'section',
    stem: "A buyer wants to take over a seller's existing mortgage. Which feature of that loan would block the assumption?",
    options: [
      'A prepayment penalty',
      'An alienation (due-on-sale) clause',
      'An escrow account',
      'Private mortgage insurance',
    ],
    correct: 1,
    explanation: 'A loan is assumable precisely because it lacks an alienation clause (also called a due-on-sale clause) — the provision that would otherwise let the lender demand full repayment when the property changes hands.',
    difficulty: 'application',
    source: 'reader: temporary authority & on the job · assumable loans',
  },
  {
    id: 'temporary-authority-and-the-job-x06',
    unitId: 'temporary-authority-and-the-job',
    moduleId: 'uniform-state-content',
    area: 'ust',
    pool: 'section',
    stem: "On a single loan, an originator is already paid by the borrower and now also wants a payment from the lender. Under the CFPB Loan Originator Rule cross-referenced here, what is that?",
    options: [
      'Allowed as long as it is disclosed',
      'Allowed if the two payments are equal',
      'Prohibited dual compensation — an originator cannot be paid by both the borrower and another party on the same loan',
      'Governed by the SAFE Act exam-retake rule',
    ],
    correct: 2,
    explanation: "The CFPB Loan Originator Rule bars dual compensation: an originator can't be paid by both the borrower and another party on the same loan.",
    difficulty: 'analysis',
    source: 'reader: temporary authority & on the job · the loan-originator rule (see Module 3)',
  },
];

export default bank;
