import type { ExamItem } from '@/content/exam/types';

const bank: ExamItem[] = [
  {
    id: 'the-safe-act-x01',
    unitId: 'the-safe-act',
    moduleId: 'uniform-state-content',
    area: 'ust',
    pool: 'section',
    stem: "A newly hired MLO breaks a lending law because his broker never bothered to train him. Under the doctrine the SAFE Act leans on, who else can be held accountable?",
    options: [
      'The employer, even though the violation traced back to poor training',
      'The borrower who accepted the loan',
      'The NMLS as the registry operator',
      'No one — accountability stops with the individual originator',
    ],
    correct: 0,
    explanation: "Under respondeat superior ('let the master answer'), the SAFE Act spreads accountability upward: when an originator breaks the law, the employer can be held responsible too, even when the violation came from poor training.",
    difficulty: 'recall',
    source: 'reader: the SAFE Act · what the SAFE Act changed',
  },
  {
    id: 'the-safe-act-x02',
    unitId: 'the-safe-act',
    moduleId: 'uniform-state-content',
    area: 'ust',
    pool: 'section',
    stem: "A consumer wants to know which organizations actually built and run the registry where she can look up her loan officer. What is the correct answer?",
    options: [
      'The CFPB and the FBI',
      'The Conference of State Bank Supervisors (CSBS) and the American Association of Residential Mortgage Regulators (AARMR)',
      'The OCC and the FDIC',
      'Fannie Mae and Freddie Mac',
    ],
    correct: 1,
    explanation: 'The NMLS was built and is run by two bodies working together: the Conference of State Bank Supervisors (CSBS) and the American Association of Residential Mortgage Regulators (AARMR).',
    difficulty: 'recall',
    source: 'reader: the SAFE Act · the NMLS',
  },
  {
    id: 'the-safe-act-x03',
    unitId: 'the-safe-act',
    moduleId: 'uniform-state-content',
    area: 'ust',
    pool: 'section',
    stem: "An MLO changes employers and moves from Ohio to Texas. What happens to her NMLS unique identifier?",
    options: [
      'Texas issues her a brand-new number',
      'It reverts to her Social Security number for the new state',
      'It stays the same — the number is permanent across employers and states',
      'It is deleted until she re-registers in Texas',
    ],
    correct: 2,
    explanation: "The unique identifier is permanent: change employers or states and the number stays the same, which is exactly what makes cross-country tracking possible. It is deliberately never the Social Security number.",
    difficulty: 'application',
    source: 'reader: the SAFE Act · the unique identifier',
  },
  {
    id: 'the-safe-act-x04',
    unitId: 'the-safe-act',
    moduleId: 'uniform-state-content',
    area: 'ust',
    pool: 'section',
    stem: "An MLO is designing new business cards and a billboard advertisement. Under the SAFE Act, what must she do with her unique identifier?",
    options: [
      'Keep it confidential and never place it in public view',
      'Display it on her applications, solicitations, and advertising, and share it with anyone who asks',
      'Show it only on the signed loan application',
      'Replace it with her Social Security number on public materials',
    ],
    correct: 1,
    explanation: 'An originator must display the unique identifier on their applications, solicitations, and advertising, and share it with anyone who asks. It is meant to be public, which is why it is never the SSN.',
    difficulty: 'application',
    source: 'reader: the SAFE Act · the unique identifier',
  },
  {
    id: 'the-safe-act-x05',
    unitId: 'the-safe-act',
    moduleId: 'uniform-state-content',
    area: 'ust',
    pool: 'section',
    stem: "An agent brings a buyer and seller together, does no financing work, and is not paid by any lender or broker for a loan. Under the SAFE Act, what is she?",
    options: [
      'Not a loan originator at all',
      'A registered loan originator',
      'A state-licensed loan originator',
      'A supervised loan processor',
    ],
    correct: 0,
    explanation: 'A real-estate agent doing brokerage work is outside the loan-originator definition unless a lender or broker pays them for the loan. Because no one paid her for financing, she is not a loan originator.',
    difficulty: 'application',
    source: 'reader: the SAFE Act · who counts as a loan originator',
  },
  {
    id: 'the-safe-act-x06',
    unitId: 'the-safe-act',
    moduleId: 'uniform-state-content',
    area: 'ust',
    pool: 'section',
    stem: "Before 2008, an originator who cheated could resign, cross a state line, and start over untracked. Which SAFE Act feature most directly slammed that escape hatch shut?",
    options: [
      'The requirement that loans be 30-year fixed-rate products',
      'The single national NMLS record that follows an originator across states and employers',
      'The exemption for timeshare credit',
      'The doctrine of respondeat superior',
    ],
    correct: 1,
    explanation: 'State-by-state oversight let bad actors escape. The single national registry gives every originator a permanent record that follows them across states and jobs, so misconduct stays visible anywhere. Respondeat superior spreads blame to employers but does not track originators across state lines.',
    difficulty: 'analysis',
    source: 'reader: the SAFE Act · the NMLS',
  },
];

export default bank;
