import type { ExamItem } from '@/content/exam/types';

const bank: ExamItem[] = [
  {
    id: 'tila-x01',
    unitId: 'tila',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: 'A borrower is reviewing her closing costs. Which of these charges is NOT part of the finance charge?',
    options: [
      'The interest she will pay over the loan’s life',
      'The discount points she paid to buy down her rate',
      'The property taxes owed on the home',
      'The lender’s origination fee',
    ],
    correct: 2,
    explanation: 'The test is simple: if you would pay the charge even in an all-cash purchase, it is not a finance charge. Property taxes are owed whether or not you borrow, so they are out. Interest, points, and the lender’s own fees all exist because you are borrowing, so they are finance charges.',
    difficulty: 'recall',
    source: 'reader: TILA · the finance charge',
  },
  {
    id: 'tila-x02',
    unitId: 'tila',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: 'Two days after closing on the purchase-money loan for his new home, a buyer gets cold feet and wants to unwind the loan under TILA’s right of rescission. Can he?',
    options: [
      'Yes — he has three business days to rescind any home loan',
      'Yes, but only if the lender failed to deliver the required disclosures',
      'No — a purchase-money loan is final at closing; rescission covers refinances and home-equity loans on a principal dwelling',
      'No — rescission only applies to second homes and investment properties',
    ],
    correct: 2,
    explanation: 'You cannot rescind a loan used to buy a house — a purchase-money loan is final the moment it closes. The right of rescission applies to a refinance or home-equity loan on the borrower’s principal dwelling. Rescission specifically excludes second homes and investment properties, so that option is backwards.',
    difficulty: 'recall',
    source: 'reader: TILA · the right of rescission',
  },
  {
    id: 'tila-x03',
    unitId: 'tila',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: 'A homeowner refinanced her principal residence, but the lender never properly delivered the notice of right to cancel. She wants to rescind six months later. Is the window still open?',
    options: [
      'No — the window closed three business days after settlement regardless',
      'Yes — because the notice was never given, the window stays open up to 3 years after consummation (or until she sells or transfers the home)',
      'Yes, but only for 20 calendar days after she discovers the problem',
      'No — the only remedy is a refund of the finance charge',
    ],
    correct: 1,
    explanation: 'The three-day clock only starts if the lender properly delivers the notice of right to cancel and the material cost disclosures. When it doesn’t, the window stays open for up to 3 years after consummation, or until the home is sold or transferred. The 20-calendar-day period is the lender’s deadline to return money after a rescission, not the borrower’s window to rescind.',
    difficulty: 'application',
    source: 'reader: TILA · when a missing notice reopens the window',
  },
  {
    id: 'tila-x04',
    unitId: 'tila',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: 'A subordinate-lien mortgage carries an APR that is 3.6 percentage points above the Average Prime Offer Rate. Under TILA, how is it classified?',
    options: [
      'Not an HPML — subordinate liens are exempt from HPML rules',
      'A Higher-Priced Mortgage Loan, because a subordinate lien crosses at 3.5 points over APOR',
      'Not an HPML — the subordinate-lien threshold is 6.5 points',
      'A high-cost (Section 32) loan, because it exceeds 3.5 points',
    ],
    correct: 1,
    explanation: 'A subordinate lien becomes an HPML at 3.5 percentage points over APOR, and 3.6 exceeds that. First-lien conforming loans cross at 1.5 and jumbos at 2.5; there is no 6.5-point HPML threshold (6.5 is HOEPA’s first-lien rate trigger). Crossing an HPML line does not by itself make the loan a Section 32 high-cost loan.',
    difficulty: 'application',
    source: 'reader: TILA · higher-priced mortgage loans',
  },
  {
    id: 'tila-x05',
    unitId: 'tila',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: 'A mortgage broker proposes to be paid more when he places a borrower in a loan with a higher interest rate. Is that compensation structure allowed under TILA?',
    options: [
      'Yes, as long as the borrower consents in writing',
      'No — an originator’s pay cannot be based on a loan’s terms, such as the interest rate',
      'Yes, because the interest rate is set by the market, not the broker',
      'No, but only if the broker is also paid directly by the borrower',
    ],
    correct: 1,
    explanation: 'An originator’s pay can’t be based on a loan’s terms — not the interest rate or any feature that varies deal to deal — because paying more for a higher rate rewards the originator for making the loan worse. Pay can be a fixed percentage of the loan amount, which is not a "term." Borrower consent doesn’t cure it, and the dual-compensation bar is a separate rule.',
    difficulty: 'application',
    source: 'reader: TILA · how originators get paid',
  },
  {
    id: 'tila-x06',
    unitId: 'tila',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: 'An appraisal comes in lower than the loan needs. The lender asks the appraiser to consider several additional comparable sales and to explain how she reached her conclusion. Does this cross TILA’s appraiser-independence line?',
    options: [
      'Yes — any contact with the appraiser after a low value is coercion',
      'No — asking the appraiser to weigh additional comps or explain a conclusion is permitted quality control',
      'Yes — the lender must instead order a second appraisal every time',
      'No — but only if the lender first pays a bonus for reaching the target value',
    ],
    correct: 1,
    explanation: 'Ordinary quality control stays allowed: asking the appraiser to weigh additional comparable sales, correct a genuine error, or explain a conclusion, and ordering a second valuation when the first looks unreliable. What is prohibited is coercing, bribing, threatening, or conditioning pay on hitting a number — such as paying a bonus for a target value, which would be a clear violation.',
    difficulty: 'analysis',
    source: 'reader: TILA · appraiser independence',
  },
];

export default bank;
