import type { ExamItem } from '@/content/exam/types';

const bank: ExamItem[] = [
  {
    id: 'trid-x01',
    unitId: 'trid',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: 'A settlement agent hands the borrower the Closing Disclosure in person at the office. Under TRID, how soon after that can the loan be consummated?',
    options: [
      'The same day, since it was delivered in person',
      'At least 3 precise business days after the borrower receives it',
      'At least 6 precise business days after the borrower receives it',
      'At least 7 precise business days after the borrower receives it',
    ],
    correct: 1,
    explanation: 'The borrower must receive the CD at least 3 precise business days before consummation. The 6-day figure applies when the CD is mailed or sent electronically (3 for delivery plus 3 to review) unless receipt is confirmed sooner. The 7-day floor is the separate minimum between Loan Estimate delivery and closing.',
    difficulty: 'recall',
    source: 'reader: TRID · the closing disclosure clock',
  },
  {
    id: 'trid-x02',
    unitId: 'trid',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: 'A lender has just issued the Loan Estimate. The borrower has not yet said she intends to proceed. What is the only fee the lender may charge her at this point?',
    options: [
      'A loan application fee',
      'The actual cost of the credit report',
      'A non-refundable appraisal deposit',
      'A rate-lock fee',
    ],
    correct: 1,
    explanation: 'After issuing the LE, the lender may not charge any fee — beyond the actual cost of pulling the credit report — until the borrower states an intent to proceed. Application, appraisal, and rate-lock fees all have to wait for that statement of intent.',
    difficulty: 'recall',
    source: 'reader: TRID · before the lender can charge you',
  },
  {
    id: 'trid-x03',
    unitId: 'trid',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: 'Between the Loan Estimate and the Closing Disclosure, a transfer tax rises by $200 with no valid change of circumstance. Who absorbs the increase?',
    options: [
      'The borrower, because taxes are outside the lender’s control',
      'The lender, because a transfer tax is a zero-tolerance charge',
      'It is split evenly between borrower and lender',
      'The borrower, as long as the total 10% bucket stays under 110%',
    ],
    correct: 1,
    explanation: 'A transfer tax sits in the zero-tolerance bucket — fees the lender controls can’t rise a dollar, so the lender eats the increase. It is not in the 10% aggregate bucket, and it is not a no-tolerance item like property taxes or insurance. Absent a valid change of circumstance, the borrower pays nothing extra here.',
    difficulty: 'application',
    source: 'reader: TRID · the three tolerance buckets',
  },
  {
    id: 'trid-x04',
    unitId: 'trid',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: 'Just before closing on a fixed-rate loan, the final APR comes in 0.20% higher than the APR disclosed on the Closing Disclosure. What happens?',
    options: [
      'A corrected CD is handed over at the table with no new waiting period',
      'A new Closing Disclosure is required and the full 3-day waiting period restarts',
      'Nothing — APR changes never restart the clock',
      'The clock only restarts if the change exceeds 0.25%',
    ],
    correct: 1,
    explanation: 'On a fixed-rate loan, an APR that moves more than 0.125% forces a new CD and resets the full 3-day clock. A 0.20% increase exceeds that, so a fresh three days is owed. The 0.25% tolerance applies to ARMs, not fixed-rate loans. Only minor changes get a corrected CD at the table without a new wait.',
    difficulty: 'application',
    source: 'reader: TRID · what restarts the three-day clock',
  },
  {
    id: 'trid-x05',
    unitId: 'trid',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: 'Midway through a transaction, the title company the borrower selected goes out of business, and replacement title fees come in higher. Is this a valid change of circumstance that lets the fees move?',
    options: [
      'No — the borrower chose the title company, so the lender must absorb it',
      'Yes — the chosen title company closing mid-transaction is one of the five valid changes of circumstance',
      'No — only a natural disaster qualifies as a valid change of circumstance',
      'Yes, but only if the lender first wanted to earn more on the loan',
    ],
    correct: 1,
    explanation: 'The five valid changes of circumstance include the chosen title company going out of business mid-deal. When one occurs, the tolerance limits are suspended, the borrower pays the item’s true cost, and a revised Loan Estimate is issued. A natural disaster is only one of the five, and a lender simply wanting more revenue is never a VCOC.',
    difficulty: 'application',
    source: 'reader: TRID · what lets a fee change',
  },
  {
    id: 'trid-x06',
    unitId: 'trid',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: 'From the Loan Estimate to the Closing Disclosure, one recording fee in the 10% bucket jumped 20%, but the bucket’s total rose only 6% because another fee came in low. Has the tolerance been breached?',
    options: [
      'Yes — any single fee rising more than 10% breaches the tolerance',
      'No — the 10% bucket is tested in aggregate, and the total stayed under 110%',
      'Yes — recording fees are always zero-tolerance',
      'No — but only because the borrower chose the recording provider',
    ],
    correct: 1,
    explanation: 'The 10% bucket isn’t checked fee by fee — it is checked in total. The borrower can be charged up to 110% of the disclosed total, so one fee can overshoot as long as another keeps the group under 110%. A 6% aggregate rise is within bounds. Recording fees sit in the 10% bucket, not zero-tolerance, and the aggregate test — not who chose the provider — is what governs.',
    difficulty: 'analysis',
    source: 'reader: TRID · how the 10% test works',
  },
];

export default bank;
