import type { ExamItem } from '@/content/exam/types';

const bank: ExamItem[] = [
  {
    id: 'usa-patriot-act-x01',
    unitId: 'usa-patriot-act',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: "A new lending office is setting up its lobby. Under its Customer Identification Program, what notice must the institution post there?",
    options: [
      'A notice that it will require identification to open an account or apply for a loan',
      'A notice listing its current interest rates',
      "A notice of the borrower's right to rescind",
      "A notice of the institution's privacy policy",
    ],
    correct: 0,
    explanation: "The CIP requires the institution to post a lobby notice that it will ask for identification. Rate sheets, rescission notices, and privacy notices come from other rules, not the PATRIOT Act's identity-verification duty.",
    difficulty: 'recall',
    source: 'reader: USA PATRIOT Act · knowing exactly who you\'re lending to',
  },
  {
    id: 'usa-patriot-act-x02',
    unitId: 'usa-patriot-act',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: "A brand-new applicant who is not already a customer applies for a mortgage. What must the loan originator collect to verify identity under the CIP's mortgage steps?",
    options: [
      'Two years of tax returns',
      'A valid government-issued photo ID whose picture clearly resembles the applicant',
      'A notarized letter from a reference',
      'A co-signer with an established account',
    ],
    correct: 1,
    explanation: "For anyone not already a customer, the originator must collect a valid, government-issued photo ID whose picture clearly resembles the person, then attest under penalty of law that identity was verified. Tax returns, reference letters, and co-signers are not the CIP identity step.",
    difficulty: 'application',
    source: 'reader: USA PATRIOT Act · the mortgage identity steps',
  },
  {
    id: 'usa-patriot-act-x03',
    unitId: 'usa-patriot-act',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: "A borrower whose identity the institution already verified for an earlier account applies for a new loan. Must they prove their identity all over again under the CIP?",
    options: [
      'Yes — every new loan requires fresh identity verification',
      'No — someone already verified as an existing customer need not re-prove identity',
      'Yes — but only a photo ID is required the second time',
      'No — but only if the loan is under $10,000',
    ],
    correct: 1,
    explanation: "The CIP applies to anyone opening an account or applying for a loan, but someone already verified as an existing customer does not have to prove their identity again. There is no dollar-based exception to this in the unit.",
    difficulty: 'application',
    source: 'reader: USA PATRIOT Act · knowing exactly who you\'re lending to',
  },
  {
    id: 'usa-patriot-act-x04',
    unitId: 'usa-patriot-act',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: "Screening an applicant, an institution finds the person on a government list of known or suspected terrorists. What does the CIP require?",
    options: [
      'Proceed with the loan but charge a higher rate',
      'Not open the account or make the loan',
      'Require a larger down payment and proceed',
      'Proceed but monitor the account closely',
    ],
    correct: 1,
    explanation: "A match on a government terrorist watch list is a hard stop: no financial institution may open an account or make a loan for anyone on such a list. Adjusting the rate, down payment, or monitoring does not permit a prohibited transaction.",
    difficulty: 'application',
    source: 'reader: USA PATRIOT Act · the watch lists',
  },
  {
    id: 'usa-patriot-act-x05',
    unitId: 'usa-patriot-act',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: "A credit bureau receives a written certification from a government agency conducting an authorized international-terrorism investigation and turns over a consumer's file. What must the bureau do about telling the consumer?",
    options: [
      'It must promptly notify the consumer of the request',
      'It may not disclose to the consumer that the file was requested or obtained',
      'It must note the access in the consumer report',
      'It must charge the consumer a fee for the disclosure',
    ],
    correct: 1,
    explanation: "The bureau must stay silent: it may not tell the consumer — or note in the report — that a government agency requested or obtained access to the file. Notifying the consumer or recording the access would be exactly what the Act forbids.",
    difficulty: 'analysis',
    source: 'reader: USA PATRIOT Act · credit files and terror investigations',
  },
  {
    id: 'usa-patriot-act-x06',
    unitId: 'usa-patriot-act',
    moduleId: 'federal-mortgage-laws',
    area: 'federal',
    pool: 'section',
    stem: "At application, a mortgage lender hands every applicant a document explaining that identification is required. What is that document called?",
    options: [
      'The Patriot Act Information Disclosure',
      'The Loan Estimate',
      'The Special Information Booklet',
      'The Currency Transaction Report',
    ],
    correct: 0,
    explanation: "At application the lender gives every applicant the Patriot Act Information Disclosure, explaining that identification is required. The Loan Estimate, Special Information Booklet, and CTR come from other laws entirely.",
    difficulty: 'recall',
    source: 'reader: USA PATRIOT Act · the mortgage identity steps',
  },
];

export default bank;
