import type { ExamItem } from '@/content/exam/types';

const bank: ExamItem[] = [
  {
    id: 'va-and-usda-x01',
    unitId: 'va-and-usda',
    moduleId: 'general-mortgage-knowledge',
    area: 'general',
    pool: 'section',
    stem: "A client compares an FHA loan with a VA loan and asks how the federal government stands behind each. How should the originator describe the difference?",
    options: [
      'The government insures both loans',
      'The FHA loan is insured; the VA loan is guaranteed',
      'The VA loan is insured; the FHA loan is guaranteed',
      'The government guarantees both loans',
    ],
    correct: 1,
    explanation: 'An FHA loan is insured by the federal government through HUD, while a VA loan is guaranteed by the Department of Veterans Affairs — the agency covers part of the lender\'s loss rather than insuring the loan. The exact word matters; VA and USDA guarantee, FHA insures.',
    difficulty: 'recall',
    source: 'reader: VA & USDA · how the four programs differ',
  },
  {
    id: 'va-and-usda-x02',
    unitId: 'va-and-usda',
    moduleId: 'general-mortgage-knowledge',
    area: 'general',
    pool: 'section',
    stem: "A veteran buying with a VA loan puts nothing down and asks why the lender doesn't require mortgage insurance the way a conventional loan would. What stands in for it?",
    options: [
      'Private mortgage insurance is deferred',
      'A one-time VA funding fee, backed by the VA guaranty',
      'An FHA mortgage insurance premium',
      'A larger residual-income cushion',
    ],
    correct: 1,
    explanation: 'VA loans prohibit mortgage insurance altogether. Instead the borrower pays a one-time VA funding fee at settlement, which the VA pools to reimburse lenders on default, and the government guaranty covers part of the loss. PMI and FHA MIP belong to other programs.',
    difficulty: 'application',
    source: 'reader: VA & USDA · no PMI — a funding fee instead',
  },
  {
    id: 'va-and-usda-x03',
    unitId: 'va-and-usda',
    moduleId: 'general-mortgage-knowledge',
    area: 'general',
    pool: 'section',
    stem: "A veteran was rated by the VA with a 30% service-connected disability and is buying a home with a VA loan. What happens with the funding fee?",
    options: [
      'It is charged at the standard first-use rate',
      'It is waived — the veteran is exempt',
      'It is doubled because of the higher risk',
      'It must be paid in cash at closing',
    ],
    correct: 1,
    explanation: 'A veteran with a service-connected disability of 10% or more is exempt from the funding fee, as are Purple Heart recipients and certain surviving spouses. A 30% rating clears the 10% threshold, so no funding fee is owed.',
    difficulty: 'application',
    source: 'reader: VA & USDA · who skips the funding fee',
  },
  {
    id: 'va-and-usda-x04',
    unitId: 'va-and-usda',
    moduleId: 'general-mortgage-knowledge',
    area: 'general',
    pool: 'section',
    stem: "An underwriter is qualifying a VA borrower and notices the borrower's housing (front-end) ratio is high. How does the VA treat that ratio?",
    options: [
      "It caps the front-end ratio at 41%",
      "It ignores the front-end ratio and looks at back-end DTI plus residual income",
      "It requires the front-end ratio under 28%",
      "It averages the front-end and back-end ratios",
    ],
    correct: 1,
    explanation: "Unlike every other program, the VA doesn't look at the front-end (housing) ratio at all. It considers only a back-end DTI, generally up to 41%, which can stretch higher when residual income — money left after mandatory expenses — is strong.",
    difficulty: 'application',
    source: 'reader: VA & USDA · how the VA underwrites',
  },
  {
    id: 'va-and-usda-x05',
    unitId: 'va-and-usda',
    moduleId: 'general-mortgage-knowledge',
    area: 'general',
    pool: 'section',
    stem: "A non-veteran assumes a veteran's VA mortgage. The original veteran later applies for a new VA loan and is told they can't get one yet. Why?",
    options: [
      'The veteran is still liable for the assumed debt',
      "The veteran's COE stays attached to the assumed loan until it's paid in full",
      'A veteran may never obtain more than one VA loan in a lifetime',
      'The assumption stripped the veteran of their entitlement permanently',
    ],
    correct: 1,
    explanation: "Because the assuming non-veteran has no COE of their own, the original veteran's COE stays attached to the assumed loan until it is paid in full, so that veteran can't get another VA loan meanwhile. The veteran is not, however, still liable for the debt.",
    difficulty: 'analysis',
    source: 'reader: VA & USDA · assumable — with the COE attached',
  },
  {
    id: 'va-and-usda-x06',
    unitId: 'va-and-usda',
    moduleId: 'general-mortgage-knowledge',
    area: 'general',
    pool: 'section',
    stem: "A household earning well above the area median wants a USDA Guaranteed Rural Housing loan on a home in an approved rural area. Why might they still be turned down?",
    options: [
      "USDA loans require at least 5% down",
      "Their income exceeds 115% of the adjusted area median income",
      "USDA loans can't be used on primary residences",
      "USDA loans carry no mortgage insurance",
    ],
    correct: 1,
    explanation: 'The USDA program is income-tested: a household\'s income may not exceed 115% of the adjusted area median income (AMI). Being in an approved rural locale alone isn\'t enough if the income cap is exceeded.',
    difficulty: 'application',
    source: 'reader: VA & USDA · the income cap that keeps it targeted',
  },
];

export default bank;
