import type { ExamItem } from '@/content/exam/types';

const bank: ExamItem[] = [
  {
    id: 'who-needs-a-license-x01',
    unitId: 'who-needs-a-license',
    moduleId: 'uniform-state-content',
    area: 'ust',
    pool: 'section',
    stem: "An MLO originates loans for a federally regulated credit union. Regarding state licensing, what is his status?",
    options: [
      'A state-licensed loan originator who must earn a state license',
      'A registered loan originator who registers in the NMLS but needs no state license',
      'Exempt from the NMLS entirely',
      'Not a loan originator at all',
    ],
    correct: 1,
    explanation: 'A credit union is a depository institution (an exempt entity), so its originator is a registered loan originator: registered in the NMLS with a unique identifier, but not state-licensed, because a federal banking agency already supervises the employer.',
    difficulty: 'recall',
    source: 'reader: who needs a license · registered versus licensed',
  },
  {
    id: 'who-needs-a-license-x02',
    unitId: 'who-needs-a-license',
    moduleId: 'uniform-state-content',
    area: 'ust',
    pool: 'section',
    stem: "A bank's MLO and a mortgage broker's MLO disagree about who needs a state license. Which requirement do they both share regardless of employer?",
    options: [
      'Both must hold a state license',
      'Both must be registered in the NMLS with a unique identifier',
      'Both must be licensed attorneys',
      'Both are exempt from any registration',
    ],
    correct: 1,
    explanation: 'Every loan originator must be registered in the NMLS with a unique identifier — that part is universal. Whether they also need a state license on top of that depends entirely on who they work for.',
    difficulty: 'recall',
    source: 'reader: who needs a license · opening',
  },
  {
    id: 'who-needs-a-license-x03',
    unitId: 'who-needs-a-license',
    moduleId: 'uniform-state-content',
    area: 'ust',
    pool: 'section',
    stem: "A homeowner negotiates a mortgage on the very house she lives in, for herself. Does she need an MLO license?",
    options: [
      'No — negotiating a loan on your own residence is exempt',
      'Yes — all mortgage negotiation requires a license',
      'Only if the loan amount exceeds a set threshold',
      'Only if a depository institution is the lender',
    ],
    correct: 0,
    explanation: 'A few individuals can arrange a mortgage without a license because they are not in the business of it — including negotiating a loan on a home that is your own residence.',
    difficulty: 'application',
    source: 'reader: who needs a license · the individual exemptions',
  },
  {
    id: 'who-needs-a-license-x04',
    unitId: 'who-needs-a-license',
    moduleId: 'uniform-state-content',
    area: 'ust',
    pool: 'section',
    stem: "An attorney negotiates a mortgage as an incidental part of representing a client, but a lender agrees to pay her for arranging that loan. What is the licensing result?",
    options: [
      'She remains exempt because she is a licensed attorney',
      'She remains exempt because the work is incidental',
      'The exemption disappears and a license is required',
      'She is exempt only if the client also consents',
    ],
    correct: 2,
    explanation: 'A licensed attorney is exempt when negotiating a mortgage as an incidental part of representing a client — unless a lender or broker is paying the attorney for it, in which case the exemption disappears.',
    difficulty: 'application',
    source: 'reader: who needs a license · the individual exemptions',
  },
  {
    id: 'who-needs-a-license-x05',
    unitId: 'who-needs-a-license',
    moduleId: 'uniform-state-content',
    area: 'ust',
    pool: 'section',
    stem: "An independent 1099 loan processor works on files for properties located in three different states, under no originator's supervision. What does licensing require of him?",
    options: [
      'Nothing — processors are always exempt',
      'A single federal processor license',
      'He must be licensed in every state where the subject properties are located',
      'Registration in the NMLS but never a license',
    ],
    correct: 2,
    explanation: 'A contract (1099) processor or underwriter working independently rather than as a supervised employee must be licensed in every state where the properties they work on are located.',
    difficulty: 'application',
    source: 'reader: who needs a license · processors and underwriters',
  },
  {
    id: 'who-needs-a-license-x06',
    unitId: 'who-needs-a-license',
    moduleId: 'uniform-state-content',
    area: 'ust',
    pool: 'section',
    stem: "Two MLOs do identical work: one at a national bank needs no state license, the other at a mortgage broker does. What best explains the difference?",
    options: [
      'The bank originator earns less, so oversight is lighter',
      'A federal banking agency already supervises the bank, while no such regulator sits over the broker',
      'The broker writes riskier loans than the bank',
      'The bank originator skipped NMLS registration',
    ],
    correct: 1,
    explanation: "A federal banking agency already supervises the bank, so the state need not license its originator. No such regulator sits over the broker, so the state licenses that originator directly.",
    difficulty: 'analysis',
    source: 'reader: who needs a license · registered versus licensed',
  },
];

export default bank;
